### ISSUE TITLE
`kexec_kernel` only exports the pool containing the selected BE

### ISSUE THREAD

**Issue by ahesford** [zbm-dev/zfsbootmenu#105]
We do a good job of cleaning up ZFS mounts throughout ZBM, mounting and unmounting only around the specific parts where we need filesystem access. We are not so careful with r/w pool imports (and cannot be, unless we want to annoy users with endless encryption prompts). Once a pool is imported r/w, it stays that way unless explicitly reimported.

In `kexec_kernel`, we export the pool containing the selected BE if that pool is mounted r/w. Best practice is probably to loop through all pools and export every r/w pool before doing the final `kexec`. This might require some care in case one or more exports fail or, if possible, the kexec were to fail.

**Comment by zdykstra** [comment]
The work for this is staged in the `logging` branch.

**Comment by zdykstra** [comment]
Closed in https://github.com/zbm-dev/zfsbootmenu/commit/45d00665c57715efa72215f61990e4c45fd68939
