### ISSUE TITLE
Relocate some scripts to /libexec

### ISSUE THREAD

**Issue by ahesford** [zbm-dev/zfsbootmenu#110]
In pushing to support remote control of ZBM over SSH and dynamic startup and shutdown hooks, I put the `zfsbootmenu-countdown` script and the hook directories under `/libexec` because these scripts are not intended to be run by the user, and user interaction through the shell takes on greater significance over SSH. It would be nice to carry this over to the other non-interactive scripts:
- [x] `zfsbootmenu-input`
- [x] `zfsbootmenu-preview.sh` (why does this get a `.sh` extension when the others have them stripped?)

That leaves `zfs-chroot` (which I forget exists, but is nice to have), `zfsbootmenu-help` and `zfsbootmenu` in `/bin` where they belong.

**Comment by zdykstra** [comment]
Started this work in https://github.com/zbm-dev/zfsbootmenu/tree/helper-cleanup
