### ISSUE TITLE
Explore moving fzf/sk keybinds to the caller

### ISSUE THREAD

**Issue by zdykstra** [zbm-dev/zfsbootmenu#116]
Instead of hard-coding keybinds in the `draw_` functions, possibly pass them in so they're defined closer to the caller.

**Comment by ahesford** [comment]
I'm going to give this some though, but I'm not convinced there's an elegant way to accomplish ths. We'd have to handle the header text and the `expect` argument, which would get unwieldy. Maybe we could make something work by trying to scrape the header entries for `Alt+<char>` labels and automatically populate `expect`, but I don't like the fragilitty.

**Comment by ahesford** [comment]
I don't see an elegant way to manage this, and there isn't a compelling reason to pursue an inelegant solution.
