### ISSUE TITLE
How to set final kernel parameters?

### ISSUE THREAD

**Issue by Matthew-Tate-Scarbrough** [zbm-dev/zfsbootmenu#117]
Thank you all for the speedy answers on the keymap issue, but one last question and I will be satisfied.

If I am understanding how ZBM works, the boot parameters set for ZBM do not affect the final boot after entering in the passphrase for the encrypted ZFS root. So then, how would one passthrough kernel parameters for the final boot?

**Comment by zdykstra** [comment]
The easiest way to do that is `zfs set org.zfsbootmenu:commandline="your kernel command line" zroot` and it'll set it for all boot environments.

**Comment by Matthew-Tate-Scarbrough** [comment]
Thank you, to be absolutely clear, does it matter if you have set previous params? will they maintain? (I assume so).

I asked because I saw that construction in the instructions for Void Linux.

**Comment by zdykstra** [comment]
The `zfs set` command will remove any previous options and replace them with whatever you've now entered. You can use `zfs get org.zfsbootmenu:commandline zroot` (or possibly zroot/ROOT, depending on where you set it last) to see what the previous value was.

**Comment by Matthew-Tate-Scarbrough** [comment]
Great, that is simple:

1. `zfs get org.zfsbootmenu:commandline <root dataset>` — or — `cat /proc/cmdline` to get all previously set params
2. `zfs set org.zfsbootmenu:commandline "<previous options> <new options>" <root dataset>` to set the new params.

Then a reboot should be fine, correct? no need to reconfigure ZBM? (though it wouldn't hurt).

**Comment by zdykstra** [comment]
> Great, that is simple:
> 
>     1. `zfs get org.zfsbootmenu:commandline <root dataset>` — or — `cat /proc/cmdline` to get all previously set params
> 
>     2. `zfs set org.zfsbootmenu:commandline "<previous options> <new options>" <root dataset>` to set the new params.
> 
> 
> Then a reboot should be fine, correct? no need to reconfigure ZBM? (though it wouldn't hurt).

That's exactly right, yup. Don't set the `root=` option, that will be filled in by ZFSBootMenu when it sets up the `kexec` command.

You don't need to rebuild/recreate ZBM, that value is read from the ZFS filesystem on each boot. Remember that ZFS properties are inherited and the more-specific instance takes precedence. So if you set an option on `zroot/ROOT`, but also set one on `zroot/ROOT/be`, the value on `zroot/ROOT/be` will be the one that is used.

**Comment by Matthew-Tate-Scarbrough** [comment]
Thank you, I was assuming that was the case.
