### ISSUE TITLE
Menu mapping doesnt respect custom keymap

### ISSUE THREAD

**Issue by eoli3n** [zbm-dev/zfsbootmenu#124]
I use https://github.com/eoli3n/void-config/blob/master/scripts/install/02-install.sh#L148 to configure ``azerty`` keymap for zfsbootmenu, which works, as keymap is azerty when i type my passphrase.

```
# Config keymap as https://github.com/zbm-dev/zfsbootmenu/issues/96#issuecomment-745627427
mkdir -p /mnt/etc/cmdline.d
echo 'rd.vconsole.keymap=fr' > /mnt/etc/cmdline.d/keymap.conf
echo 'install_optional_items+=" /etc/cmdline.d/keymap.conf "' > /mnt/etc/zfsbootmenu/dracut.conf.d/keymap.conf
```

Except, you told me to use an undocumented [ALT+W] combo to mount RW.
It didn't work, but [ALT+Z] did.
Menu alt combos doesnt respect keymap.

**Comment by eoli3n** [comment]
If i run the following in recovery shell, it triggers the problem. Alt-w does nothing, alt-z stop it
```
printf "%s\n" a b c d e f g | fzf --expect alt-w
```

**Comment by eoli3n** [comment]
``generate-zbm`` with ``hostonly="yes"`` didn't solve it.

**Comment by zdykstra** [comment]
After quite a bit of testing and debugging this issue, @ahesford, @ericonr and I have tracked this down to specifically the `alt` key handling under the `fr` keymap. (`ctrl-<key>` works correctly under `fr`) Can you try changing the keymap to `azerty` in `/etc/cmdline.d/keymap.conf`, re-run `generate-zbm` and try again?

@ahesford and I are working on a more permanent solution, but it will take a bit of time to implement it cleanly.

**Comment by eoli3n** [comment]
When i change in ``/etc/cmdline.d/keymap.conf``
```
rd.vconsole.keymap=fr
```
to
```
rd.vconsole.keymap=azerty
```
My keyboard fallback in qwerty as typing my passphrase on my azerty keyboard doesnt work.
