### ISSUE TITLE
Unable to unlock zpool with keylocation pointing to partition on USB stick

### ISSUE THREAD

**Issue by sxc731** [zbm-dev/zfsbootmenu#127]
The use-case is to leverage a decryption key stored on a removable USB stick for a headless server by making use of [this little trick](https://github.com/openzfs/zfs/issues/6556#issuecomment-497010957).  Admittedly this doesn't appear to be properly supported by ZFS at present, since it relies on setting `keyformat=passphrase` rather than smth more appropriate, such as `raw`.  Nevertheless this works a treat: a pool set up in this manner unlocks automatically so long as the suitable USB stick is plugged into the box at boot time.

Unfortunately, ZBM struggles somewhat with this.  As far as I can tell, the issue is that `load-key()` in `zfsbootmenu-lib.sh` wants to actually find the file referenced in `keylocation`; if it can't, it drops down to the penultimate line in that function, which presents a prompt.

I've implemented a workaround, which is to run `zfs load-key -a` at the beginning of `load-key()` (before the test that checks if the filesystem is actually encrypted).  This works fine for my use case but I'm not sure if this could cause any unpleasant side-effects in other scenarios?  Is there an issue with attempting to load all available keys (in the absence of any, perhaps?) and/or could this load too many keys?  

I did try the suggestion to replace the `-f` at https://github.com/zbm-dev/zfsbootmenu/blob/master/90zfsbootmenu/zfsbootmenu-lib.sh#L1381 with a `-e`, to no avail.

Here's some info  about the encrypted pool's setup:
```
# zfs list -o name,mountpoint,encroot,keystatus,keylocation,keyformat
NAME                                MOUNTPOINT                ENCROOT    KEYSTATUS  KEYLOCATION                           KEYFORMAT
apool                               none                      apool      available  file:///dev/disk/by-partlabel/my-key  passphrase
apool/HOME                          none                      apool      available  none                                  passphrase
apool/HOME/root_2021-01-02T11:20    /root                     apool      available  none                                  passphrase
apool/ROOT                          none                      apool      available  none                                  passphrase
apool/ROOT/ubuntu_2021-01-02T11:20  /                         apool      available  none                                  passphrase
```
Without the workaround, in ZBM's emergency shell after I beat the passphrase prompt about 5 times, `zpool list` shows the pool online (unlocked) and the datasets are also shown; however, unless I issue `zfs load-key -s` in the emergency shell, I can't boot.

More context can be found [here](https://www.reddit.com/r/zfs/comments/ki9oun/pseudo_raid1_with_zfs_async_replication_to_2nd/ghvip1c?utm_source=share&utm_medium=web2x&context=3).

**Comment by zdykstra** [comment]
Thanks for opening the ticket. Since it sounds like you are able to boot with out issue, this isn't an emergency to get resolved immediately. We'll try to get this labbed up in our testing environment this week to see what can be done for a permanent solution.

**Comment by ahesford** [comment]
It seems the value of using `keyformat=passphrase` is allowing more than 32 random characters.

Using `load-key-a` is bad in general because it will try to load every key possible. In my personal setup, I have several encryption roots, many with different passphrases, that I wouldn't want to be tasked with unlocking at each boot.

I don't think Line 1381 in `zfsbootmenu-lib.sh` is sufficient to swap `-f` for `-e`. Please make the same change at Lines 1367 and 1388. Those two should be relevant and sufficient for your use.

**Comment by sxc731** [comment]
> I don't think Line 1381 in `zfsbootmenu-lib.sh` is sufficient to swap `-f` for `-e`. Please make the same change at Lines 1367 and 1388. Those two should be relevant and sufficient for your use.

You're right and sorry, I should have spotted those: with those three `-f` swapped for `-e`'s everything works as expected; many thanks!  It seems this is now a straightforward change that shouldn't entail too much regression risk and could be included in a forthcoming milestone?

**Comment by ahesford** [comment]
Thanks for confirming that the fix works. The next release should work out of the box for you.
