### ISSUE TITLE
CTRL+E (edit kernel cmdline) no longer works on master version

### ISSUE THREAD

**Issue by sxc731** [zbm-dev/zfsbootmenu#131]
This is a regression compared to version 1.8.0.  Thankfully it's easy to fix: https://github.com/zbm-dev/zfsbootmenu/blob/ab95346f4c5b4487fd33b3c9936fd1b16f156f3b/90zfsbootmenu/zfsbootmenu-lib.sh#L199 is missing `alt-e,`

**Comment by zdykstra** [comment]
Thanks for the bug report, tracked that back to an errant change in d02865e9d0dab6bd1c3e6b592f10d9e5adb4b159 .
