### ISSUE TITLE
/usr/lib/udev is hardcoded

### ISSUE THREAD

**Issue by vozhyk-** [zbm-dev/zfsbootmenu#133]
When I run `generate-zbm` on Gentoo (`openrc`, `USE=split-usr` in case that makes a difference), I get:
```
# generate-zbm
Mounting /boot/efi
Creating ZFSBootMenu 1.8.1 from kernel /boot/vmlinuz-5.4.51-gentoo-x86_64
dracut-install: ERROR: installing '/usr/lib/udev/vdev_id'
dracut: FAILED: /usr/lib/dracut/dracut-install -D /var/tmp/dracut.djkjGC/initramfs -a /usr/lib/udev/vdev_id
dracut: failed to install essential executable '/usr/lib/udev/vdev_id'
Failed to create /tmp/mo7y7dzWV3/zfsbootmenu.efi
Unmounting /boot/efi
```

I see that `/usr/lib/udev` is hardcoded in https://github.com/zbm-dev/zfsbootmenu/blob/ac8a8edafbbcd8e22013de676982edcd590445d9/90zfsbootmenu/module-setup.sh . If I change every `/usr/lib/udev` to `/lib/udev`, the problem goes away.

**Comment by zdykstra** [comment]
Thank you for opening this issue. I'll get a more permanent fix for you to test later today.

**Comment by ahesford** [comment]
Upstream ZFS uses some placeholder strings and replaces them on install, that's probably a good approach here too.

**Comment by vozhyk-** [comment]
Looks like `genkernel` (which I use for the initramfs) finds the directory using `pkg-config`: https://github.com/gentoo/genkernel/blob/369cfa98f72675a285ec98439e9054ab57b234c9/gen_funcs.sh#L1142
