### ISSUE TITLE
Detect EFI stub binary from systemd-boot

### ISSUE THREAD

**Issue by vozhyk-** [zbm-dev/zfsbootmenu#135]
`generate-zbm` tries to find the EFI stub binary at `/usr/lib/gummiboot/linuxx64.efi.stub` by default and fails on my system, as I have `systemd-boot`, not `gummiboot`, installed.

It works if I specify the `systemd-boot` location of the binary in the config:
```
sed -i -e '/EFI:/a\  Stub: /usr/lib/systemd/boot/efi/linuxx64.efi.stub' /etc/zfsbootmenu/config.yaml
```

It would be nice to not have to configure this.

I see that `dracut` is supposed to guess the location by itself if it is not specified, but doesn't (https://bugs.gentoo.org/765208; same on my system with `dracut` version `050`).

**Comment by ahesford** [comment]
It looks like dracut does as advertised; it looks first to the systemd location and falls back to the gummiboot location when `--uefi-stub` is not supplied on the command line. It seems reasonable for `generate-zbm` to omit the `--uefi-stub` command line when a specific value is not specified in the configuration and let dracut do its thing.

**Comment by vozhyk-** [comment]
I see, `dracut` works as advertised on your system. Then that bug might be specific to Gentoo.

**Comment by ahesford** [comment]
Sorry---I haven't verified it actually runs properly without `--uefi-stub`, I was just looking through the `dracut` script and everything seems reasonable. More testing is definitely warranted to determine whether the script works as it seems.

**Comment by ahesford** [comment]
Not sure if it's relevant in your case, but if dracut can't use `pkg-config` to find the systemd path, it uses the parent of `[/usr]/lib/systemd/systemd-udevd` [as the $systemdutil path](https://github.com/dracutdevs/dracut/blob/master/dracut.sh#L1100-L1106). If this path doesn't exist, `$systemdutildir` will not be defined, and [dracut will look for the EFI stub](https://github.com/dracutdevs/dracut/blob/master/dracut.sh#L1181-L1188) at either `/boot/efi/linuxx64.efi.stub` or `/usr/lib/gummiboot/linuxx64.efi.stub`.

**Comment by vozhyk-** [comment]
Thanks for looking into this in depth. I see now that on my system, neither of those exists:
```
# pkg-config systemd --variable=systemdutildir
Package systemd was not found in the pkg-config search path.
Perhaps you should add the directory containing `systemd.pc'
to the PKG_CONFIG_PATH environment variable
No package 'systemd' found
# ls /lib/systemd/systemd-udevd
ls: cannot access '/lib/systemd/systemd-udevd': No such file or directory
# ls /usr/lib/systemd/systemd-udevd
ls: cannot access '/usr/lib/systemd/systemd-udevd': No such file or directory
```
And the `systemd-boot` package doesn't install any pkg-config file.

I'll take this to the Gentoo bug linked above.
