### ISSUE TITLE
Pass root=ZFS= to the BE kernel on Gentoo

### ISSUE THREAD

**Issue by vozhyk-** [zbm-dev/zfsbootmenu#136]
I'm using `genkernel` to create the initramfs in the BE (which gets kexec'd by `zfsbootmenu`). That initramfs only accepts a ZFS root option in the form of `root=ZFS=<dataset>` or `root=ZFS`. If an option of the form `root=zfs:<dataset>` is supplied, it fails to boot.

I have set `org.zfsbootmenu:rootprefix="root=ZFS="` on `<pool>/ROOT`, and this fixed the problem.

Not having to configure this would be nice.

**Comment by vozhyk-** [comment]
One way would be to make the `root=ZFS=<dataset>` format the default, at least in Gentoo.

I initially thought this wouldn't make sense on Gentoo, since people use different initramfs generators, but it seems only one I know of uses a different format, which is neither of the two.

- GRUB2 passes `root=ZFS=<dataset>`: https://git.savannah.gnu.org/gitweb/?p=grub.git;a=blob;f=util/grub.d/10_linux.in;h=e8b01c0d0c71cf1f85d95d73d204e09dc8ad7eba;hb=refs/heads/master#l76
- `dracut` (also popular in Gentoo) appears to accept `root=ZFS=<dataset>`: https://github.com/openzfs/zfs/blob/60a2434b295f395bbedcec2c4cd6a54530edf29a/contrib/dracut/90zfs/parse-zfs.sh.in#L31

The one using a different format is `bliss-initramfs` (which I used to use a long time ago for ZFS on LUKS) - and it seems to take `root=<dataset>` now: https://github.com/fearedbliss/bliss-initramfs/blob/master/USAGE.md#general

By the way, `initramfs-tools` (which is used in Ubuntu, IIRC), also accepts `root=ZFS=<dataset>` along with `root=zfs:<dataset>`: https://github.com/openzfs/zfs/blob/60a2434b295f395bbedcec2c4cd6a54530edf29a/contrib/initramfs/scripts/zfs#L755

**Comment by vozhyk-** [comment]
Another way would be to read the initramfs image and try to guess what generated it - `lsinitrd` from `dracut` shows the contents of files in `/lib/dracut` in the image:
```
# lsinitrd /boot/initramfs-5.4.51-gentoo-x86_64.img
initrd in UEFI: : 14M
========================================================================
Version: Genkernel 3.5.2.5-848-g78db2b9-git (2021-01-16 16:22:18 UTC)
<...>
```
```
# lsinitrd /boot/efi/EFI/zfsbootmenu/initramfs-bootmenu.img
initrd in UEFI: : 43M
========================================================================
Early CPIO image
========================================================================
<...>
========================================================================
Version: dracut-050
<...>
```
This would probably lengthen the boot time, though.

**Comment by zdykstra** [comment]
https://github.com/zbm-dev/zfsbootmenu/blob/master/90zfsbootmenu/zfsbootmenu-lib.sh#L707 just needs to be extended to support Gentoo. If you can post the contents of `/etc/os-release`, we can add support for it.

**Comment by vozhyk-** [comment]
Thanks, here it is:
```
# cat /etc/os-release
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo/Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
```

**Comment by zdykstra** [comment]
Excellent, thank you!
