### ISSUE TITLE
Nvidia troubles on zfsbootmenu, it seems

### ISSUE THREAD

**Issue by RoundDuckKira** [zbm-dev/zfsbootmenu#141]
I use Project Trident, and at the feeling this may be an upstream issue with zfsbootmenu, I decided to post here. There's a reddit post about it that I'll link to where I compiled all my information at. https://old.reddit.com/r/techsupport/comments/l3zwbk/sidetopic_hardware_nvidia_umm_i_have_been_having/

it's closed but only so because of trouble with this problem and the feeling this will take a lot longer to fix than I hope. But basically it seems that Nvidia GPUs don't function at all after boot and can't display, even though the driver is in the kernel enough to at least have an attempt to initialize. I tried various kernel cmdline configurations as listed in a comment, and yet had the same problems. 

This may still be an issue with PT though so I'm still asking them on their Telegram, but might as well get an issue up and running in case there's issues upstream.

Oh btw this is a laptop GPU, a 1050 Ti laptop GPU to be more exact.

**Comment by ahesford** [comment]
First, I would try forcefully excluding any Nvidia or nouveau drivers from your ZFSBootMenu image and maybe booting ZFSBootMenu with `nomodeset`. Removing the drivers probabaly consists of creating some new conf file in `/etc/zfsbootmenu/dracut.conf.d`, for example, `/etc/zfsbootmenu/dracut.conf.d/nvidia.conf` and adding a line like
```bash
omit_drivers+=" nouveau nvidia "
```
(I don't use Nvidia drivers so I am not sure about the name; you might need to extra `nvidia*` drivers too.)

Afterwards, do `lsinitrd /boot/efi/path/to/zfsbootmenu.img` to see if there are any remaining `nouveau` or `nvidia` kernel extensions in `/lib/modules`. If so, add those to the blacklist and try again. Once the ZFSBootMenu initramfs is clear of any Nvidia drivers, the hope is that ZBM will launch without initializing any Nvidia hardware, so the final kernel you boot can do the job.

**Comment by RoundDuckKira** [comment]
> First, I would try forcefully excluding any Nvidia or nouveau drivers from your ZFSBootMenu image and maybe booting ZFSBootMenu with `nomodeset`. Removing the drivers probabaly consists of creating some new conf file in `/etc/zfsbootmenu/dracut.conf.d`, for example, `/etc/zfsbootmenu/dracut.conf.d/nvidia.conf` and adding a line like
> 
> ```shell
> omit_drivers+=" nouveau nvidia "
> ```
> 
> (I don't use Nvidia drivers so I am not sure about the name; you might need to extra `nvidia*` drivers too.)
> 
> Afterwards, do `lsinitrd /boot/efi/path/to/zfsbootmenu.img` to see if there are any remaining `nouveau` or `nvidia` kernel extensions in `/lib/modules`. If so, add those to the blacklist and try again. Once the ZFSBootMenu initramfs is clear of any Nvidia drivers, the hope is that ZBM will launch without initializing any Nvidia hardware, so the final kernel you boot can do the job.

and this would only apply to the zfsbootmenu and not anything booted from it like my system?

**Comment by ahesford** [comment]
Yes, ZBM uses a segregated configuration because it relies on its own module that is mutually exclusive with the standard ZFS dracut module and also to accommodate situations where the configuration of ZBM should be different from the ordinary initramfs.

Once you pick a kernel to boot, ZBM loads that and the normal initramfs to finish the boot process.

**Comment by RoundDuckKira** [comment]
thanks @ahesford and also @zdykstra who came in at the PT Telegram. If this fixes it I'll close it.

**Comment by RoundDuckKira** [comment]
it works, thanks! :D But... not closing the issue yet, thinking of making my third contribution to some open source project with a minor contribution to the readme, give me time for me to propose an idea tho...

**Comment by RoundDuckKira** [comment]
#142 should solve this issue now, will close when it's accepted
