### ISSUE TITLE
Kernel-log viewer issues

### ISSUE THREAD

**Issue by ahesford** [zbm-dev/zfsbootmenu#149]
The new kernel log viewer has two issues that should be addressed before the next release:
1. The `fzf` binding for this (`Ctrl-L`) uses the `refresh-preview` action, which is relatively new and not provided in `fzf-0.20.0` included with Ubuntu Focal Fossa. This causes a hard failure when trying to show the boot menu, with the screen repeatedly printing "unknown action: refresh-preview" because `fzf` is dying.
2. Warnings don't seem to be shown properly with Ubuntu's dmesg. With a `readonly=on` pool, select a BE and use `Ctrl+I` to get an interactive (read-only) chroot. When returning to the menu screen, a yellow `[!]` appears in the preview pane to indicate a warning, but pressing `Ctrl+L` shows an empty log. Dropping to a recovery shell and looking at `dmesg` reveals the warning is "ZFSBootMenu: read-write mount of ztest/ROOT/ubuntu forbidden, pool ztest is not writable".

Regarding issue (1), I don't really have a good solution. Without `refresh-preview` in the binding, the warning/error indicator remains after viewing logs, until the menu selection changes or `Esc` is used to refresh the view by killing `fzf`. It is obviously desirable to update the preview after leaving the log viewer. We could do version comparisons (horrible) or use a command like
```bash
echo "abc" | fzf -f "abc" --bind "alt-l:refresh-preview" --exit-0 >/dev/null 2>&1
```
which seems to return 0 (when the "abc" strings match), 1 when the string isn't found, and 2 when `refresh-preview` isn't a recognized action. This is non-ideal but is less horrible than version comparisons. We can do it at runtime when picking the fuzzy finder or we could do it at module-setup time, but we'd have to provide some kind of trigger file to indicate the refresh-preview is available and that starts to look hacky.

Regarding issue (2), I believe this is caused because Ubuntu's `dmesg` does not support `--noescape`, so `dmesg` errors out when invoked. I believe all other options we use for log review are supported there. Looks like we're back to more feature discovery.

@zdykstra

**Comment by zdykstra** [comment]
I'd be okay with doing feature discovery at build time, provided we have an easy mechanism for it. 

We could simply write a key/value pair config file to `/etc/zfsbootmenu.conf` in the initramfs from `module-setup.sh` and then source it at runtime to enable toggles/code paths. We already do this in some fashion for LE/BE, it'd just be extending the mechanism to a more formal position within ZBM.

**Comment by zdykstra** [comment]
I think we'll have to disable warning indicators if `fzf` isn't new enough. Optionally turning that feature off in `zfsbootmenu-preview.sh` will be fairly easy.

**Comment by zdykstra** [comment]
For the second one, we can disable color codes when writing `debug`-level messages, and then drop the `--noescape` flag on older versions of `dmesg`. We'll want the color/nocolor test to be fast, so we don't add even more time spent in `log()` at the `debug` log level.

**Comment by zdykstra** [comment]
Fixed in https://github.com/zbm-dev/zfsbootmenu/commit/dee62289c471e7f304e81978a563b31304beb99e
