### ISSUE TITLE
"no sysroot.mount exists for zfs-generator did not extend it"

### ISSUE THREAD

**Issue by dm17** [zbm-dev/zfsbootmenu#159]
Followed this guide on a new system using musl & encryption:
https://github.com/zbm-dev/zfsbootmenu/wiki/Void-Linux---Single-disk-UEFI

At boot it says:
"no sysroot.mount exists for zfs-generator did not extend it"

I'm not sure why or where to start. I'll try to re-install from scratch tomorrow in case there's some user error I missed... I'm not sure if it is the same problem:
https://github.com/openzfs/zfs/issues/8343

**Comment by ahesford** [comment]
Are you getting the ZFSBootMenu countdown screen or a menu showing the boot environments? If so, ZBM should be working properly, and you might be able to fix this issue right from ZFSBootMenu and avoid a reinstall.

To attempt a fix like the one in the issue you linked, just chroot into your new Void install:
1. If you see the ZFSBootMenu countdown, press `Esc` to drop the the menu.
2. If you have more than one boot environment in the menu, select the one you need to fix.
3. Press `Ctrl-W` to re-import your pool with write privileges. (This is a hidden hotkey.) If your BE or pool are encrypted, you might have to re-enter your passphrase. You will know the operation succeeded because the preview at the top of your screen will switch from green to red, and the header will say `r/w` in place of `r/o`.
4. Jump into the chroot with `Ctrl-I`.
5. Move the ZFS cache out of the way: `mv /etc/zfs/zpool.cache /etc/zfs/zpool.cache.old`.
6. Regenerate your initramfs images.  For every kernel package you have installed of the form `linuxX.Y` (or at least the ones you want to boot), run `xbps-reconfigure -f linuxX.Y`.
7. Exit the chroot.
8. Try to boot the selected environment.

**Comment by dm17** [comment]
> Are you getting the ZFSBootMenu countdown screen or a menu showing the boot environments? If so, ZBM should be working properly, and you might be able to fix this issue right from ZFSBootMenu and avoid a reinstall.
> 
> To attempt a fix like the one in the issue you linked, just chroot into your new Void install:
> 
> 1. If you see the ZFSBootMenu countdown, press `Esc` to drop the the menu.
> 2. If you have more than one boot environment in the menu, select the one you need to fix.
> 3. Press `Ctrl-W` to re-import your pool with write privileges. (This is a hidden hotkey.) If your BE or pool are encrypted, you might have to re-enter your passphrase. You will know the operation succeeded because the preview at the top of your screen will switch from green to red, and the header will say `r/w` in place of `r/o`.
> 4. Jump into the chroot with `Ctrl-I`.
> 5. Move the ZFS cache out of the way: `mv /etc/zfs/zpool.cache /etc/zfs/zpool.cache.old`.
> 6. Regenerate your initramfs images.  For every kernel package you have installed of the form `linuxX.Y` (or at least the ones you want to boot), run `xbps-reconfigure -f linuxX.Y`.
> 7. Exit the chroot.
> 8. Try to boot the selected environment.

Thanks a lot - I'd like to learn to fix it this way.
1) done
2) just the one root install (followed instructions to the tee)
3) ctrl-w -> isn't working for me.

After the first failure (with "no sysroot.mount exists for zfs-generator did not extend it" after the import), now when I press enter on zfsbootmenu: I get immediately into "Launching emergency shell: unable to successfully import a pool."

**Comment by ahesford** [comment]
I'm not sure why `Ctrl-w` would fail. In ZBM, if you are forced to an emergency shell, you can do `zpool import` to see what is available to import and try `zpool import -a -N` to try importing all pools. These might give you useful error messages to diagnose an issue.

If the import succeeds, you can type `exit` in the emergency shell to return to the menu and use `Ctrl-I` to get into the chroot. From there, you can try removing the `zpool.cache` file.

I wonder if this is a hostid issue, which is common on musl systems.

**Comment by dm17** [comment]
@ahesford Thanks! Now it looks like it did on my first boot:
I was able to import in emergency shell using: ```zpool import -a -N -f```
then I typed ```exit```
then I got the password prompt. When I typed the password correctly, I got the same error and was told to look at /run/initramfs/rdsosreport.txt, which says, in part:
```
dracut: ZFS: Importing pool zroot...
... some USB stuff...
dracut: ZFS: Mounting dataset zroot/ROOT/void.2021.03.09...
dracut: NO sysroot.mount exists or zfs-generator did not extend it.
dracut: ZFS: Mounting root with the traditional mount-zfs.sh instead.
```
... same 3 lines repeat until it says:
```dracut Warning: Can't mount root filesystem```

Should I try to remove this zpool.cache in the emergency shell before booting into rootfs? Will wait to hear back before continuing since I'm a bit lost. This guide worked perfectly on another system (but I did use glibc that time) - and like you said, I'm wondering where the more relevant error message is.
Thanks! :)

**Comment by dm17** [comment]
Actually, before it talks about ```/run/initramfs/rdsosreport.txt``` it outputs a lot of:
```
filesystem `root/ROOT/void.2021.03.09' can not be mounted: Permission denied
Encrypted ZFS password for zroot: key load error: Failed to open key material file.
Wrong password
```
The first time I did this guide, I thought I might have missed the chmod 000 step on the key file... But I went back to the live distro & imported the pool, found the keyfile, outputted it to verify, and then chmod'd 000... Not what it could be yet.

**Comment by ahesford** [comment]
This sounds like you forgot to include the key file in your initramfs. In the naming scheme of the guide, you should have

    install_items+=" /etc/zfs/zroot.key "

in your `/etc/dracut.conf.d/zol.conf`. If not, add it and regenerate your initramfs.

Either way, you should confirm that your initramfs contains the key file with, *e.g.*,

    lsinitrd /boot/initramfs-5.10.22_1.img

or whatever kernel version you have.

**Comment by zdykstra** [comment]
Feel free to re-open this issue if you continue to have issues now that 1.9.0 is out.

**Comment by dm17** [comment]
@zdykstra @ahesford 
I ended up re-installing from scratch because I couldn't figure out how to get my bearings to continue an install. I ended up having the exact same issue, but now I'm more certain that I did it correctly. First, here are the confounding factors that confused me so much the first time around:

1)
```
echo "cannot have $ in it" > /etc/zfs/zroot.key
```
This is why I tried to fix my install the first time. However, I could not fix it because [of this issue](https://stackoverflow.com/questions/41641450/how-to-destory-zfs-phantom-pool-after-re-installing-zfs-pool):
2)
Basically, when you try to create/import/export a ZFS pool that has the same name as one that was somehow hanging around from a previous install - even after destroying all partitions with gdisk - then it finds multiple and doesn't know which to import. So I got around this by zeroing the disk with dd.
3)
Minor, but worth mentioning that I had to add a nameserver in resolv.conf after entering the chroot in order to xbps-install -S

So, the only other changes I made to the install guide were:
1) Adding musl here:
```XBPS_ARCH=x86_64-musl xbps-install -S -R https://mirrors.servercentral.com/voidlinux/current/musl -r /mnt base-system vim efibootmgr gptfdisk linux5.4 linux5.4-headers
2) Omitting ```Configure your glibc locale``` because it doesn't seem relevant to musl installations.

Now I'm basically at the same point as before. When I enter the correct password, I get a screen full of:
```
dracut: ZFS: Mounting dataset zroot/ROOT/void.2021.05.01...
[bunch of usb stuff, not relevant]
dracut: ZFS: No sysroot.mount exists or zfs-generator did not extend it.
dracut: ZFS: Mounting root with the traditional mount-zfs.sh instead
[it repeats a lot...]
```

**Comment by zdykstra** [comment]
You can use `wipefs` to remove all traces of ZFS (or really, any filesystem) from a disk. It knows how to remove all of the signatures that ZFS creates.

The ZFS dracut module is failing for you, so it could be any number of different things. Can you establish the flow here, so I can make sure we're troubleshooting in the correct spot?

* Are you booting with EFI (rEFInd, direct EFI boot, etc) ?
* Can you boot to the main ZFSBootMenu / see the countdown ?
* Do you get a password prompt either after the countdown, or before you get to the main menu?
* When you get to the main ZFSBootMenu screen, please record the command line it's going to use when booting your boot environment, and note it here.
* From the main menu, hit ALT+R to get to a recovery shell, and then run:
  `zfs list -o name,canmount,mountpoint,encroot,keystatus,keylocation,org.zfsbootmenu:keysource`
  `zpool list`

Lastly, when the initramfs gets to the repeat loop, does it ever time out (might take a few minutes) and drop you to an emergency shell?

**Comment by dm17** [comment]
> You can use `wipefs` to remove all traces of ZFS (or really, any filesystem) from a disk. It knows how to remove all of the signatures that ZFS creates.
> 
> The ZFS dracut module is failing for you, so it could be any number of different things. Can you establish the flow here, so I can make sure we're troubleshooting in the correct spot?
> 
> * Are you booting with EFI (rEFInd, direct EFI boot, etc) ?
Yes, I followed the entire tutorial to the tee, except for the musl changes I made (cited previously). Now that I think of it there is one other: I changed one parameter in the ```zpool create``` block you made: compression. I set it to ```zstd```.

> * Can you boot to the main ZFSBootMenu / see the countdown ?
I selected "boot to menu" this time - and I see that after entering the password, I can get to ZBM!

> * Do you get a password prompt either after the countdown, or before you get to the main menu?
I'm not sure what countdown you're referring to... There was one in refind, which would boot to "Void".

> * When you get to the main ZFSBootMenu screen, please record the command line it's going to use when booting your boot environment, and note it here.

At the top in green:
```zroot/ROOT/void.2021.05.01 (default, encrypted, r/o) - vmlinuz-5.11.17_1```
Below that in white:
```ro quiet spl.spl_hostid=some_hex_number```
To the left in yellow (with red prompt):
```zroot/ROOT/void.2021.05.01```


> * From the main menu, hit ALT+R to get to a recovery shell, and then run:
>   `zfs list -o name,canmount,mountpoint,encroot,keystatus,keylocation,org.zfsbootmenu:keysource`
```
NAME                                      CANMOUNT  MOUNTPOINT  ENCROOT  KEYSTATUS KEYLOCATION
zroot                                       on                 none               zroot          available    file:///etc/zfs/zroot.key
zroot/ROOT                             on                 none               zroot          available    none
zroot/ROOT/void.2021.05.01  noauto          /                      zroot          available    none
zroot/home                             on                 /home             zroot          available    none
```
The last column under ORG.ZFSBOOTMENU:KEYSOURCE, they all show a dash like "-"


>   `zpool list`
Shows the volume as I set it up (abbreviated):
```
zroot  correct-size  1.5G used  capacity is 0%, dedup is 1.00x, health is "ONLINE" ALTROOT is "-"
```

> 
> Lastly, when the initramfs gets to the repeat loop, does it ever time out (might take a few minutes) and drop you to an emergency shell?

Yes in less than 5 seconds of mostly showing this:
```
filesystem 'zroot/ROOT/void.2021.05.01' can not be mounted: permission denied
encrypted zfs password for root: key load error: failed to open key material file
```

**Comment by dm17** [comment]
I just tried [the instructions](https://github.com/zbm-dev/zfsbootmenu/issues/159#issuecomment-797063726) @ahesford left above. I was able to xbps-reconfigure -f 5.11. Then when I booted in it did behave differently (took longer to quit, was less verbose) - but had all of the same errors.

**Comment by zdykstra** [comment]
Based on the error message, it looks like your final initramfs is missing `/etc/zfs/zroot.key` . On the main ZFSBootMenu screen, you can hit `CTRL+W` and then `CTRL+I` to enter a read-write chroot of your boot environment. Does the file `/etc/zfs/zroot.key` exist, with your zpool password in it and does `/etc/dracut.conf.d/zol.conf` have `install_items+=" /etc/zfs/zroot.key "` in it? Both of those need to be present for dracut to install the item in your initramfs. 

You can use `cd /boot ; lsinitrd` <your most recent initramfs> | grep zroot.key` to ensure the file is present.

**Comment by dm17** [comment]
@zdykstra Super, yes, those both exist. Surprisingly the ```$``` char is in the password. There's something wrong with having dollar signs in these or something. I just want to remove it. Can I just change the contents of ```/etc/zfs/zroot.key``` to change the volume's password?

**Comment by zdykstra** [comment]
ZFS shouldn't care at all that there's a `$` in your password. Is the key file actually present in your initramfs? When you boot the system and it eventually errors out and drops you to an emergency shell after saying that it can't mount `zroot/ROOT/void.2021.05.01`, you should be able to `cat /etc/zfs/zroot.key` and confirm that the file is there and that it has your password in it.

To actually change the passphrase for an encryption root, you'll need to use `zfs change-key`, which can only be done after you've loaded the correct key through some mechanism. That can be done from the emergency chroot in ZFSBootMenu, but lets avoid muddying the waters with that until it's absolutely needed.

**Comment by dm17** [comment]
@zdykstra Yes ```cd /boot ; lsinitrd <your most recent initramfs> | grep zroot.key``` shows ```etc/zfs/zroot.key```

Here is the strange thing. Let's say the password in the zroot.key is ```abc$def```. The password that works to get in is actually ```abcef``` - yes, minus ```$d```. Does that make sense?

**Comment by zdykstra** [comment]
Yes, when $<something> is encountered in a double-quoted string, variable expansion occurs. You'll need to use `echo 'my password has $ in it'` to avoid expanding the unintentional variable, or escape the $ with `\$`.  So it looks like we just need to change your passphrase now to a new value and get that synchronized everywhere. I'll follow up here in a bit with the `zfs change-key` steps you'll need to take - it shouldn't be too hard to get it all done from the ZFSBootMenu recovery shell!

**Comment by dm17** [comment]
You're a legend @zdykstra

**Comment by zdykstra** [comment]
This looks to be relatively easy to accomplish. On the main ZFSBootMenu screen, hit `CTRL+W` and then `CTRL+I` to get into a read-write chroot for your boot environment. You should receive a password prompt to unlock the pool, so now your key is loaded in memory.

```
echo 'my new password' > /etc/zfs/zroot.key
zfs change-key zroot
zfs unload-key zroot
zfs load-key zroot
```
If you can make it through each of these steps successfully, your pool key is now set to the value in the `/etc/zfs/zroot.key`. From  there, run `xbps-reconfigure -f linux5.11` to force a recreation of the boot environment initramfs. At this point, you can exit the recovery shell and proceed with booting the boot environment. Please let me know if any of these steps fails for you.

**Comment by dm17** [comment]
@zdykstra first 2 commands went fine. Then on ```zfs unload-key zroot``` I get ```key unload error: 'zroot' is busy```

**Comment by zdykstra** [comment]
Whoops, my mistake - sorry!. You won't be able to unload the key when you're in a chroot of the mounted filesystem.  You should be able to now recreate the initramfs and fully boot.

**Comment by dm17** [comment]
@zdykstra Thanks a lot... Totally worked! Glad to know more about how to bootstrap my this system when things go wrong. Tools & processes like this are golden - and I hope they're here to stay!

**Comment by zdykstra** [comment]
I'm glad to hear that everything is working for you! Hopefully it's smooth sailing from here on out.

I've updated the wiki guides to use single quotes when storing the password so that empty variable expansion won't happen for passphrases with `$` in them.
