### ISSUE TITLE
One of my systems fails to boot Void Linux when the kernel is =< 5.9

### ISSUE THREAD

**Issue by ajshell1** [zbm-dev/zfsbootmenu#164]
So, my system has been using Void Linux with zfsbootmenu for a while now, but I found an issue a while back where I've found myself unable to boot anything newer than kernel 5.9. That is Kernel 5.8 works, but nothing newer does.

My system has a Ryzen 7 3700X with an ASRock Phantom 4 X570, with an ASRock Taichi 5700 XT.

I should also mention that all of my pools are unencrypted. I also have a secondary HDD pool, but I don't see how that could affect anything.

When I attempt to boot with a 5.9, 5.10 or 5.11 kernel with zfsbootmenu, my screen simply goes black and eventually the monitor powers off due to not getting any signal. I've even tried turning on the kernel flags "loglevel=7 debug" on, I don't ever see anything after booting from the zfsbootmenu screen.

However, I've found that the kernel images/whatever you want to call them boot fine when not using zfsbootmenu. I also vaguely remember that it didn't work for a few specific older kernels, but I don't remember which. I'll try testing them again after posting this issue and let you know.

My next instinct was to do a second install of Void on my zpool, but that gave me the same result.

Then, I tried installing Void with zfsbootmenu onto my Toshiba Chromebook 2 (this one: https://wiki.gentoo.org/wiki/Toshiba_Chromebook_2), but it works FINE with the latest kernel on that machine.

Next, I wiped one of the two SSDs that I boot off of on my main desktop, installed a brand new zpool on it, and tried installing Void onto that, following the guide on the wiki here. I can give you the exact commands I use to do the whole installation process if you want (since I created two shell scripts to pretty much automate the whole process).

I'm out of ideas on how to test this. I need your help. Please. I'll do anything you ask. Just please fix this.

**Comment by zdykstra** [comment]
What happens when you add 'nomodeset' to both the ZFSBootMenu command line and your BE command line? That should likely get you to the point where you can at least see a login prompt. If it does - add the following to `/etc/zfsbootmenu/dracut.conf.d/zfsbootmenu.conf`:

`omit_drivers+=" amdgpu radeon nvidia nouveau i915 "`

And then run `generate-zbm` to regenerate a new ZBM initramfs with out videocard drivers. That should be all it takes to get you going again.

**Comment by ajshell1** [comment]
That allows me to boot, but now I can't start x11 or Wayland.

**Comment by zdykstra** [comment]
`nomodeset` is a temporary step so that you can boot to a working console. After you rebuild the ZFSBootMenu initramfs, it can be removed from the command line(s). That should take care of it permanently, while still allowing you to use X11/Wayland.

**Comment by ajshell1** [comment]
Yep. That did it! Thank you so much!

Would you consider those additional lines in the `zfsbootmenu.conf` file would to the wiki?

**Comment by ahesford** [comment]
The text in https://github.com/zbm-dev/zfsbootmenu#dealing-with-driver-conflicts could be extended with comments about amdgpu and disabling mode setting in ZBM in general.

**Comment by ajshell1** [comment]
Okay. That would be enough for me. Thanks for all your help.
