### ISSUE TITLE
Single disk UEFI guide - Installing kernel 5.4

### ISSUE THREAD

**Issue by moesasji** [zbm-dev/zfsbootmenu#178]
Currently the [single disk UEFI guide](https://github.com/zbm-dev/zfsbootmenu/wiki/Void-Linux---Single-disk-UEFI) recommends the install of the 5.4 kernel, which appears outdated with 5.10 now LTS and moreover potentially unneeded seeing that [the MBR guide](https://github.com/zbm-dev/zfsbootmenu/wiki/Void-Linux----Single-disk-syslinux-MBR) installs the default kernel in base.

Would it be better to remove the recommendation to install that specific kernel version from the UEFI guide?

**Comment by ahesford** [comment]
Better? No. Worse? No.

The heading for the package list says "Adjust the mirror / libc / package selection as you see fit". If you'd like to modify the page to refer to the unversioned metapacakage, go ahead.
