### ISSUE TITLE
Arch fails to boot (when using Dracut?)

### ISSUE THREAD

**Issue by ashb** [zbm-dev/zfsbootmenu#179]
I recently upgraded from ~0.7 of zbm to 1.9, and my Arch  OS no longer booted, instead complaining about a timout on /dev/gpt-auto-root.mount.

The fix for me was to set `org.zfsbootmenu:rootprefix` to `root=zfs:`, which is the behaviour I had previously.

So maybe the setting depends not just on the OS, but on what kind of initramfs is in use?

**Comment by ahesford** [comment]
I guess you're using dracut. This behavior would be expected in that case.

You're right that adding support for Arch meant recognizing the distribution and sending a root argument compatible with the default mkinitcpio. The `org.zfsbootmenu:rootprefix` knob was exposed precisely to allow users to circumvent the automatic distribution detector and support whatever they use, even if it's non-standard.

If setting the property bothers you, you can always stick with the default mkinitcpio in your Arch BE; we require dracut to build a ZBM image, but both packages can coexist and ZBM doesn't impose any restrictions on what builds your BE initramfs images.

Another option, if you don't want two initramfs generators sitting on disk and are using UEFI, would be to go back to mkinitcpio in Arch, remove dracut and just use our pregenerated EFI executable. We intend to provide an executable with every new release and uses a generic configuration that should work in most systems.

**Comment by ashb** [comment]
I think I switched over to dracut when first trying this for the BE, as at the time it required it, but that isn't the case anymore.

I build my own zbm UEFI image as I include custom dracut module to authorize my thunderbolt dock so I can use external keyboard for passphrase entry.

I'll come up with a doc PR to fix this.

**Comment by ahesford** [comment]
I think with Arch a problem is that both `dracut` and `mkinitcpio` satisfy some virtual requirement for an initramfs generator, so if you are installing Arch and pull in `dracut` too soon, the kernel package will be satisfied and never pull `mkinitcpio`. Our Arch test environment [specifically avoids this issue](https://github.com/zbm-dev/zfsbootmenu/blob/master/testing/helpers/chroot-arch.sh#L31-L34).

**Comment by ashb** [comment]
I was quite happy with dracut after I've switched, and have actually uninstalled mkinitcpio now.

**Comment by ahesford** [comment]
Given that this is expected behavior that should be made more obvious by pending edits to the manual page, this does not seem to be a standing issue now.
