### ISSUE TITLE
Kernel panic (unable to run /sbin/init) after kexecing to the OS kernel

### ISSUE THREAD

**Issue by solbjorn** [zbm-dev/zfsbootmenu#187]
Derived from the discussion in #182.

I get a kernel error that it's unable to run /sbin/init ("_/sbin/init found, but cannot be run: error -95_") on pre-compiled ZBM 1.10.0.
The contents of my /boot folder is following (Arch Linux):

```
-rw-r--r-- 1 root root 32071096 Jun 30 19:46 initramfs-linux-xanmod-cacule-fallback.img
-rw-r--r-- 1 root root 13394075 Jun 30 19:46 initramfs-linux-xanmod-cacule.img
-rw-r--r-- 1 root root  4769792 Jun  8 20:31 intel-ucode.img
-rw-r--r-- 1 root root 11996576 Jun 30 19:46 vmlinuz-linux-xanmod-cacule
```

ZBM determines the corresponding initramfs correctly, according to its working files, so dunno what happens.
Can this be related to that I'm booting from USB-HDD and ZBM performs USB teardown prior to booting the OS?

- initramfs is built using regular mkinitcpio;
- kernel cmdline set as ZFS property doesn't contain any root or initramfs related parameters.

systemd-boot boots the kernel with this initramfs just fine if I copy them to the ESP.

**Comment by zdykstra** [comment]
Can you do a one-time edit for the kernel command line in ZFSBootMenu for that environment and append `init=/bin/sh` ? You should be able to boot to a minimal shell. I'd like to see the value of `/proc/cmdline` in your Arch BE / initramfs when you get there.

**Comment by solbjorn** [comment]
Sorry guys, that's totally my side's problem.

The root cause is in Brute LSM module, I can't say right now why it prevents kernel from executing /sbin/init (and even /sbin/sh), but it does. I will take a look at its source code a bit later.
The reason why I was booting successfully via systemd-boot is that I used `zfs=bootfs` cmdline param to boot from ZFS, and ZBM uses `root=zfs:<dataset>` to do this. For some very unclear reason kernel was booting correctly with the first variant, but with the second Brute LSM just didn't allow kernel to run executables (`-95` is `-EOPNOTSUPP`).

Thanks a lot for all the help. It's working perfectly fine now from USB-HDD with 1.10.0, without specifying any pool names or retries in the ZBM cmdline, even with ZFS version mismatch (2.0.4/5 vs 2.1.0). I like that ZBM doesn't hang or drop to emergency shell, just informs that it doesn't support some features (draid in my case, which I don't use) and continues to boot.

Closing.

**Comment by zdykstra** [comment]
Perfect. It had to be a question of different kernel command line arguments, but I wouldn't have guessed the `root=` argument as the culprit. Thank you for testing 1.10.0! We'll have a new release out soon. Once ZFS 2.1.0 is out, we'll probably tag another release to rebuild images with that in it.

**Comment by solbjorn** [comment]
ZFS 2.1.0 is out... Would you consider rebuilding the ZBM images since they were just released?

**Comment by ahesford** [comment]
We are working out a few late-breaking bugs. When these are resolved and the Void Linux ZFS package is updated (I'm testing that at the moment), we'll tag 1.10.1 with zfs-2.1.0 for future proofing.

**Comment by zdykstra** [comment]
ZFSBootMenu 1.10.1 was released earlier today. It's built with Linux kernel 5.12.14 and ZFS 2.1.0.

**Comment by solbjorn** [comment]
Thanks a lot!
