### ISSUE TITLE
spl_hostid seems to be ignored on the EFI bianary

### ISSUE THREAD

**Issue by t-oster** [zbm-dev/zfsbootmenu#191]
Hi,
first let me say thank you for this wonderful project! It is exactly what I need after I locked myself out of grub by accidentally enabling some grub-incompatible zfs feature!

I am using the stock EFI binary from the github release with arch-linux. It works well, however if I enter the menu I can see the hostid is set to 00000000, instead of my hostid deadbeef and the logs tell me to set spl_hostid=00000000 on the kcl

efiboomgr:
```
efibootmgr --disk /dev/nvme0n1 --part 1 --create --label "ZFSBootMenu" --loader '\EFI\zbm\zbm.efi' --unicode 'spl_hostid=deadbeef zbm.timeout=3 zbm.prefer=zroot zbm.import_policy=hostid'
```

hostid:
```
sudo hostid
deadbeef
```

am I doing something wrong?

**Comment by ahesford** [comment]
My guess is that you never added `/etc/hostid` to your mkinitcpio configuration. The mkinitcpio ZFS module doesn't include this file by default, which means that your root pool will always be imported with hostid 00000000.

There is a `FILES` array in your `/etc/mkinitcpio.conf` (I think this line and path are right, but I'm typing from memory here) where you can add `/etc/hostid` manually. This should cause your setup to behave as you expect.

**Comment by t-oster** [comment]
Your guess was close. I do have the /etc/hostid in the initramfs, but the initramfs is compressed via zstd (https://archlinux.org/news/moving-to-zstandard-images-by-default-on-mkinitcpio/). I guess zfsbootmenu cannot read zstd compressed initramfs, because if I change it to uncompressed, it can read the hostid.

However since I gave the hostid via parameter I would have expected that this has precedence.

Anyway, thanks for the tip.

**Comment by zdykstra** [comment]
ZFSBootMenu doesn't decompress your initramfs or read any files/values from it, it just loads it into memory for kexec.

The kernel command line value for `spl_hostid` is a hint to ZFSBootMenu, and it does initially try to use it. However, when a pool import fails it will read the hostid that was last used to import the pool, set itself to use that and then try to import the pool again.  This is the behavior enabled by `zbm.import_policy=hostid` (which is on by default in the binary releases). Despite `0xdeadbeef` being in `/etc/hostid`, your pool was actually being imported by Arch with a hostid of 0.

Is everything booting as expected for you now?

**Comment by t-oster** [comment]
ok, thank you, yes it works as expected.

**Comment by t-oster** [comment]
and thanks again for the detailed explanation and as already said: great tool!

**Comment by ahesford** [comment]
If you're in the mood for experimentation, I'd try creating a new zstd image to see if it boots. If not, try lz4 and then gzip; you shouldn't need to stick with uncompressed images.

**Comment by t-oster** [comment]
I will. I'm also planning to create a Docker file which creates the EFI image without needing to install any dependencies but allowing for tweaks like ssh Access...

**Comment by t-oster** [comment]
Hi,
I tried again with the default (zstd compressed) initrd and it works. So it seems as if you were right all along and I never imported my pool with the correct hostid, because /etc/hostid was not included in my initramfs. After inclusion, I had to reboot **twice** because after the first reboot, the pool was still last imported with the wrong hostid.
