### ISSUE TITLE
Feature Request: LVM support in the prebuilt EFI Image

### ISSUE THREAD

**Issue by glueckself** [zbm-dev/zfsbootmenu#202]
Hi!

I love how easy it is to use the pre-built EFI image, great job there!

I have one feature request, I hope this is the right place to post.

Would it be possible to include LVM support in the pre-built EFI image?
Some of my machines use ZFS on top of LVM, so they aren't able to be booted by ZBM.

(background - maybe off topic)
The reason I use ZFS on top of LVM is to make partitioning/resizing easier with LVM on top of NVMe SSDs while providing "raw" NVMe speeds for some applications (where the overhead of ZFS does get noticeable).

Thanks!

**Comment by ahesford** [comment]
I'll defer to @zdykstra, but this seems like a unique enough use case that I'd recommend building your own image.

On the master branch, you can now use Docker or podman to build images without installing a bunch of dependencies on your host system. See [releng/make-binary.sh](https://github.com/zbm-dev/zfsbootmenu/blob/master/releng/make-binary.sh) and [releng/docker/README.md](https://github.com/zbm-dev/zfsbootmenu/blob/master/releng/docker/README.md) for more details.

In the near future, we hope to provide public images on ghcr.io to make local image builds even easier.

**Comment by glueckself** [comment]
No problem, I though maybe it would be useful for others too.

I can work with that, thanks for the hints!

I'm fine with closing the issue, except if you want to find out if others would want this.

**Comment by zdykstra** [comment]
I agree with @ahesford on this request. Each new thing that is added to the pre-built images needs to be tested on our end. This would entail creating a new ZFS-on-LVM test suite for a pretty unique setup.  

The `releng` scripts should largely do what you need out-of-the-box, though you will need to play around just a bit to get the `lvm` Dracut module added in to the final build product. Let us know how it works out - and if there are any issues / documentation problems with the new containerized build system.
