### ISSUE TITLE
Feature Request: Unlocking dataset using TPM 1.2/2.0

### ISSUE THREAD

**Issue by incognitte** [zbm-dev/zfsbootmenu#205]
I would like to request a similar feature to [this guide](https://www.reddit.com/r/zfs/comments/dimtjv/guide_setting_up_tpm2based_decryption_for_zfs_on/) to be a part of ZBM.

* Unlocking automatically and booting from the ZFS root dataset using the key that are encrypted by TPM and stored either in a separate (unencrypted) dataset or stored as a part of dataset properties. 

Purpose: Provide similar functionality as Bitlocker on Windows using ZFS encrypted root and ZBM

**Comment by ahesford** [comment]
This is an interesting application of a TPM. After a quick look at the linked guide, I believe it would take careful consideration to adapt in a flexible manner, and it's probably too specialized to merit official support. We'd certainly be open to proposals if they don't require too many static assumptions about the setup.

We have a branch (to be merged eventually) that can be used to accomplish this; see the HEAD at https://github.com/zbm-dev/zfsbootmenu/commit/da23b9e4625711911885acd58a1eb5aff2ee41c9. The exmaple script in `contrib` unlocks a LUKS-encrypted keystore, but this could easily be replaced with a site-specific script to unlock some keys and copy them into the initramfs at boot. (Frankly, if I were relying on a setup like this, I'd just dump the encrypted keys to the EFI system partition or some other non-ZFS filesystem so I can mount the thing without trying to import ZFS pools.)

The biggest drawback here is that, while TPM-encrypted keys will protect filesystems should disks be removed from a system, they provide *zero* protection against somebody with physical access to the machine. A quick boot to some recovery environment (including ZBM itself) would allow an attacker to discover the cleartext passphrase and walk off with the disks.

**Comment by incognitte** [comment]
thank you @ahesford, I tried that branch, however I realized that ZBM doesn't have the hooks to use TPM for decrypting the keys, similar to what the linked guide has done.

I also agree that it needs a careful consideration as we have seen in [TrustedGRUB2](https://github.com/Rohde-Schwarz/TrustedGRUB2) there are many pieces, but I suppose they can be implemented in steps and not all features to be in a single commit.

---
On the topic of drawback that you mention, I agree with your described case, which a physical access compromises the encryption. Having said that, the bootloading supporting TPM decryption is only one loop in the chain of encrypted SDD/HDD.

I am not an expert, but based on what I have read it seems a process like below is a short TL;DR for home made encryption. In such a case physical access will not be able to decrypt `$HOME` without knowing the user login password. Any unsigned changes to the bootloader or kernel will cause the boot process to stop. Admittedly, there are many places to increase the security of this chain, but this is just as a starting point:

* EFI loads a [signed bootloader](https://medium.com/@ruchirkhatri/uefi-secure-boot-taking-control-b7a7da4c422b)
* bootloader uses [TPM to decrypt](https://www.reddit.com/r/zfs/comments/dimtjv/guide_setting_up_tpm2based_decryption_for_zfs_on/) root dataset
* bootloader verifys the [kernel's signature](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_monitoring_and_updating_the_kernel/signing-kernel-modules-for-secure-boot_managing-monitoring-and-updating-the-kernel) and passes the boot process to the kernel
* `$HOME` is in a different encrypted datasets which its key is generated as a combination of TPM and [user password](https://blog.trifork.com/2020/05/22/linux-homedir-encryption/)

**Comment by ahesford** [comment]
Using ZBM early-setup hooks to do this in a site-specific manner would take a bit of effort, but should be achievable.

Working out a general approach suitable for distribution is not a problem the maintainers are prepared to think about. While we are happy to consider pull requests that implement a solution, this is not a request that we will work on internally.

**Comment by darkbasic** [comment]
In addition it would also be interesting to use TPM to store encryption keys for SED locking ranges via (the yet to be released) cryptsetup w/ OPAL support. It will be a second layer of encryption without any kind of performance penalty.
