### ISSUE TITLE
Possible Gentoo install guide

### ISSUE THREAD

**Issue by IchikaOmamori** [zbm-dev/zfsbootmenu#212]
Hi, Is it possible to have a gentoo install guide?

**Comment by zdykstra** [comment]
Currently, none of the ZFSBootMenu maintainers have experience with Gentoo. However, there's not a lot that needs to be customized for Gentoo over any other chroot-based install guide. You'd install Gentoo on ZFS however you normally do it, but skip installing grub. Make sure you have an EFI partition. Then when it's time to install a bootloader, download the pre-built ZBM EFI bundle to your mounted ESP and configure an entry via either `efibootmgr`, or automatically via`rEFInd`.

We've merged a few small changes in the past for Gentoo support in ZFSBootMenu, so it should work out of the box for you. Feel free to reach out to the development team on libera.chat#zfsbootmenu, we can probably answer a lot of the questions that you might have while doing the install. We'd certainly welcome a how-to guide based on your experiences!
