### ISSUE TITLE
Request: help with best procedure for using a USB to enter passphrase with fallback to prompt (Debian)

### ISSUE THREAD

**Issue by Jahfry** [zbm-dev/zfsbootmenu#215]
Apologies for posting as an issue. I'm new to these parts. Didn't feel right to post on r/voidlinux. If I'm out of scope here and there's a better place for me to ask this, please chide me with a link and close this. 

...

I have a Debian 11 Bullseye system up and running via the [Debian 10 Buster](https://github.com/zbm-dev/zfsbootmenu/wiki/Debian-Buster-installation-with-ESP-on-the-zpool-disk) guide with appropriate changes. 

### What am I looking for?

* I'd like to be able to use a USB drive to unlock my passphrase, so I can be in a different room and reboot without needing to walk upstairs.
* I want to be able to remove the USB after boot and have the system stay up
* If the USB is missing on a reboot, I still want a prompt as a fallback using '/etc/zfs/zroot.key'

...

I've been reading a bit:
* [this issue](https://github.com/openzfs/zfs/issues/6556)  ... but honestly I haven't quite put the pieces from that together correctly. 
* [ArchWiki](https://wiki.archlinux.org/title/Install_Arch_Linux_on_ZFS#Loading_password_from_USB-Stick) ... to see how they do it
* [Oracle](https://docs.oracle.com/cd/E23824_01/html/821-1448/gazss.html#gdrcw) to ponder about user properties

...

Is the method used to set up Debian in the Buster guide already able to use a USB key partition but fallback to the key on the encrypted pool if USB is missing (and prompt for input) as-is?

If not, what's considered the best way for me to patch that in?

I was thinking of editing 'zfs-load-key.sh' to read in a user property (which would be set to `/dev/disk/by-id/{USBid}-part1`) and, if exists, read that. If it doesn't exist then fall back to the default method. 

But given the comments found on the [issue I mentioned](https://github.com/openzfs/zfs/issues/6556) it reads like maybe I'm being clueless and it may already work. 

Is there a guide or post that does what I'm asking?

If not, I'm heavily documenting my entire system setup and, if I get this working, will be including this as an optional step. It will go live on github once I'm done with other configurations. 

...

NOTE: I'm preferring to set my passphrase manually rather than a /dev/random so that I can remember it at the prompt. This system is a home server and VFIO host. I'm mostly going through this to add some convenience at the loss of a bit of security. I'm not worried about people in my house (wife, 3 dogs, roommate) accessing the server, I just want to be able to lock it down when we're out of town.

**Comment by ahesford** [comment]
The only thing to be aware of with the key-in-initramfs approach is that Debian (like Ubuntu and Arch) set a mode of 644 on the image by default. Any user who can read the initramfs can unpack it and gain access to the `etc/zfs/zpool.key` contained within (even if you set mode 000 on the file, as you should).

Dracut does the right thing here and explicitly sets a umask of 0077 before creating the file so only the superuser can read the image. On Void Linux, which offers mkinitcpio as an alternative to dracut, we work around the problem by forcing the right umask before we ever call the program from the automatic kernel hook.

You will probably want to find a way to always set a umask of 0077 on your initramfs from within Debian, or else you will want to inject some kind of script like the key-loading hook you write for ZBM into your Debian initramfs.

**Comment by ahesford** [comment]
If you've replaced initramfs-tools with dracut, you should be fine. Just make sure `/boot/initramfs*` is only readable by root.

**Comment by zdykstra** [comment]
If I'm understanding correctly what you'd like to do, I've mocked up / tested a bare-bones script to accomplish what you want. You'll want to create a partition on the USB drive, set a GPT label and then write junk to the entire partition. You can then pick a random offset and write your password into the drive.

```
#!/bin/bash

# fill it with junk
# dd if=/dev/urandom of=/dev/disk/by-partlabel/primary bs=1M
# write our password to a "random" location
# echo -n zfsbootmenu | dd of=/dev/disk/by-partlabel/primary bs=11 seek=1100

# shellcheck disable=SC1091
[ -f /lib/zfsbootmenu-lib.sh ] && source /lib/zfsbootmenu-lib.sh

plain="/dev/disk/by-partlabel/primary"
pass=0

while true; do
  if [ "${pass}" -gt 10 ]; then
    zinfo "timed out waiting for ${plain}"
    exit
  fi

  if [ -b "${plain}" ] ; then
    mkdir /etc/zfs
    dd if=/dev/disk/by-partlabel/primary skip=1100 bs=11 count=1 2>/dev/null > /etc/zfs/ztest.key
    exit
  else
    if delay=5 prompt="Checking for drive in %0.2d seconds" timed_prompt "[RETURN] check now" "[ESCAPE] cancel unlock" "" ; then
      pass=$((pass+1))
      continue
    else
      exit
    fi
  fi
done
```

If you're building ZFSBootMenu from master, you can then add this script to your image via:

`zfsbootmenu_early_setup="/path/to/script/raw-unlock.sh"

Just make sure it's `+x` . Let me know if this works for you, or if it's not what you were thinking of.

**Comment by Jahfry** [comment]
Wow. 

I spent most of this time (over) building a script to sanity check a LIVE USB prior to partitioning, so I hadn't gotten to where I needed to make an unlock script. So, that's great synergy for me. 

I am going under the assumption that most LIVE USBs have a ton of wasted space (example, on my 10 year old 16GB USB drive, LIVE only uses 4GB). So I'm using that extra space for more partitions. 

Your method is better than what I was going for. In mine I was going to add a 1 sector unpartitioned space before a last "filler" partition. The advantage for me was knowing where to look. The disadvantage is ... so would everyone else. 

I think I'm going to have my process do these things:

* create a 'swap' partition ... this won't actually be in use in any OS. I'll write out random to the swap to fill it with junk
* create a usable storage partition that fills the remainder
* write the passphrase to a randomized sector on the swap, possibly based on the boot drive's ID (haven't thought it through)
* add logic to the script above to find the sector to read in
* add DD to the initrd (haven't done this before but I'll figure it out)

I'll document and post the final USB creation script when done along with any modifications to your prototype. 

Thanks for the assist.

**Comment by Jahfry** [comment]
@zdykstra ...

Since I'd rather the location on the partition relate to the zroot, and not be invalidated if the current disk is replaced, I'm thinking of basing the location of the phrase on the USB on zroot's GUID. 

Any thoughts about that being good/bad?

Would allow the USB key to hide the location when it isn't attached, rather than being able to find the passphrase on the USB if you only have it but can gain access to the server later.

**Comment by zdykstra** [comment]
> @zdykstra ...
> 
> Since I'd rather the location on the partition relate to the zroot, and not be invalidated if the current disk is replaced, I'm thinking of basing the location of the phrase on the USB on zroot's GUID.
> 
> Any thoughts about that being good/bad?
> 
> Would allow the USB key to hide the location when it isn't attached, rather than being able to find the passphrase on the USB if you only have it but can gain access to the server later.
> 
> I'm able to query the GUID from an emergency shell and from the booted system, so it seems like the most stateful breadcrumb that doesn't rely on the disk ID but isn't tied to the USB.

That seems overly complicated for no real gain - though almost all of this is over-complicated for very little gain. Personally, I'd just put the ESP on a USB drive, and put your zpool key in the ZFSBootMenu EFI. When you travel / are otherwise not present, pull the USB drive out and physically secure it - in a safe, on your person, etc.

**Comment by Jahfry** [comment]
I am close to finishing up the overly complicated method I wanted, but, have a family emergency for the next week or two. I'm closing just to keep your issues cleaned up. I'll happily toss in the final as a possible contrib when I'm able to set up and polish a bit. 

Thanks for the help, sorry, forgot to do this before I hit the road.
