### ISSUE TITLE
zfs send | zfs recv/receive over a network connection?

### ISSUE THREAD

**Issue by trwnh** [zbm-dev/zfsbootmenu#227]
Is it possible to bootstrap your filesystems over a network connection, or only via a local snapshot? If it's not possible to bootstrap over the network, are there any plans to implement such functionality?

**Comment by ahesford** [comment]
It is possible, but not with the prebuilt images. @zdykstra has done this before. I usually use [hrmpf](https://github.com/leahneukirchen/hrmpf) to clone systems.

Bootstrapping from the network would require the dracut network module, drivers and possibly firmware. It also requires tooling (ssh at minimum) to be able to connect to remote systems and grab a stream. We haven't thought through a reasonable set of additions that would make this broadly useful.

**Comment by zdykstra** [comment]
I don't know if we have plans to introduce a 'GUI' way to bootstrap filesystems over the network. However, I don't think it's unreasonable that we also start shipping an EFI binary that includes a few additional tools for people - at the minimum `ip` and `dhclient`. 

`mbuffer` has a built-in network IO mode that works very very well. I've used it in the past to bootstrap a laptop from my desktop with out any real difficulties. It's what'd I'd generally recommend people use, assuming they don't need the TCP payload encrypted over the wire.

Let me see if we can come up with a heavier-weight, but still portable, EFI image for people to use. I'll follow up on this issue with a link to the GitHub Actions output for the work - we build an EFI binary and initramfs on every push to the repo.

**Comment by claudiusraphael** [comment]
@zdykstra Could you point to an (preferably in-depth) reference/tutorial on how to create such a bundle, the workflow and prerequisite knowledge and tools needed?

**Comment by trwnh** [comment]
Yeah, I downloaded the EFI binary a week ago or so to try it out and ended up not being able to do what I wanted to, so I settled for just using an old archiso I had lying around and getting zfs set up in the live environment. Having a 'GUI' way to do that would be really nice, or really, any tooling around that.

Either SSH or mbuffer would work fine, I think? mbuffer for local connections and SSH if you were an absolute madlad and needed to do it from a remote system.

Probably the most challenging thing in my recent experience was having to set all the filesystem properties again. Otherwise, it was a mostly straightforward process of just recreating the pools with the same parameters I initially used, and then doing the zfs send|recv dance over SSH -- i have a bpool and an rpool, and once those are created as empty pools all I had to do was send over .../rpool/ROOT, .../rpool/DATA, and .../bpool/BOOT from my home server. And then a bunch of `zfs set` commands.

I'll look into hrmpf in the meantime, I suppose.

**Comment by zdykstra** [comment]
I haven't forgotten about this issue/request. Work is happening on it in https://github.com/zbm-dev/zfsbootmenu/tree/you-suck-diddly-uck-flanders .

**Comment by zdykstra** [comment]
Please let me know if there are additional tools you'd like to see in the recovery images. Right now there are just a few tools to partition a disk, make either a vfat or ext4 filesystem, retrieve files via curl or send data to the system via mbuffer. All ZFS userland tools are present already. Network modules are included, allowing for the system to be booted with `ip=dhcp` on the kernel command line. There's currently no support for wireless networking, as that's a whole new can of worms.

**Comment by trwnh** [comment]
For now, the only functionality I'm interested in is ZFS send and receive over the network, as my current workflow involves booting up Arch, enabling the archzfs repos, installing zfs-linux, and manually building sanoid and its dependencies -- although it is certainly possible to just pipe zfs send and receive into mbuffer, I figured I'd script a few additional steps to be able to just use syncoid instead of bothering to take zfs snapshots manually.
