### ISSUE TITLE
pass `-a` option to kexec to support secure boot

### ISSUE THREAD

**Issue by Dragon-debian** [zbm-dev/zfsbootmenu#228]
pass `-a` option to kexec when executing kernels. this way kexexc first tires to use `KEXEC_LOAD_FILE` syscall which is necessary for secure boot, if not supported, uses old `KEXEC_LOAD` syscall.
Im tying to use zbm with secure boot. everything is ok and I can boot into zbm with secure boot turned on, my boot environments appear on screen but when I select to boot one of theme, I got an error saying  something likw`unable load kernel and initramfs`
Afe=ter that I jumped to a recover shell and mounted my zfs dataset on /mnt and then run kexec manually this way:
```
kexec -a -l /mnt/boot/vmlinuz-5.10.0-9-amd64 --initrd=/mnt/boot/initrd.img-5.10.0-9-amd64 \
      --command-line=root=zfs:rpool/ROOT/debian/default
kexec -e
```
and it boots fine.
its possible to replace `-a` with `-s` but in this case, `KEXEC_LOAD_FILE` is forced and kernels that doesnt support this, became unbootable.
Using kexec without `-a` option result in an erroe, saying something like `operation not permitted`

**Comment by Dragon-debian** [comment]
This is possible by editing line 755 of 90zfsbootmenu/zfsbootmenu-lib.sh [this is a link](https://github.com/zbm-dev/zfsbootmenu/blob/master/90zfsbootmenu/zfsbootmenu-lib.sh#L755) to that line.
I modified my `/usr/lib/dracut/modules.d/90zfsbootmenu/zfsbootmenu-lib.sh`, regenerated efi image and it works.
Sorry I dont have enough git knowledge to make a pull request.

**Comment by zdykstra** [comment]
Thank you for the bug report and the testing under Debian! I've tested this locally under non-secure boot VMs and everything looks good here.
