### ISSUE TITLE
Xen support

### ISSUE THREAD

**Issue by 0n-s** [zbm-dev/zfsbootmenu#231]
Hello!

I use ZBM happily on quite a few systems & find its kexec-based boot chain to be the most reliable, no-compromises way to boot from an encrypted disk. On some systems I also don't use ZBM, & the reason for that is that they run [Xen](https://en.wikipedia.org/wiki/Xen).

Xen, being a type 1 hypervisor, runs the Linux kernel under its kernel. This is obviously not something ZBM supports as of right now. But it can! Xen [supports kexec perfectly well](https://xenbits.xenproject.org/docs/4.2-testing/misc/kexec_and_kdump.txt), & it requires no special tooling. Not even a kexec-tools built with `--with-xen`, unless you're booting zfsbootmenu's image under Xen too[1], I believe.

Supporting Xen means:

- for zfsbootmenu to be able to use the specific kexec syntax required to boot Linux under Xen[2]
-  being able to scan for Xen kernels (generally stored in the same directory as Linux kernels, e.g.: `/boot/xen-4.14.1.gz`[3])
     * selecting the latest one automatically, like what's already done with Linux kernels
     * as well as being able to select an arbitrary combination of Xen kernel & Linux kernel, including the possibility to run without the Xen kernel
- being able to set the Xen cmdline, hopefully independently of the Linux kernel cmdline for simplicity (they're not really related)
     * default set via, say, `org.zfsbootmenu:xen_commandline` or perhaps `org.zfsbootmenu:vmm_commandline` if you think a new type 1 hypervisor that boots the exact same way will arise at some point
     * tweakable in the UI, much like the Linux kernel cmdline

& I believe this should really be all that's needed on the ZBM side. I imagine a good way to detect whether to boot the system with Xen by default is just to check for the existence of Xen kernels in the same directory as the Linux kernels. That's usually a good sign, as even distros which enable Xen support for applications (e.g. libvirt) usually don't install its kernel in the same package. Void Linux (seemingly the "home distro" of the project) follows this pattern, with the Xen kernel being in the `xen-hypervisor` package, & Xen's userspace libraries being in `xen-libs`.

[1]: I can't exactly see why one would do this (it would let you have virtual machines in…the zfsbootmenu environment, that's it). Fortunately it doesn't change kexec-tools' commandline & instead just makes it use the Xen kexec hypercall instead of the kexec system call, so ZBM doesn't need to be specifically made aware of it. As kexec-tools comes from the system, the administrator can just rebuild it with `--with-xen` if they want to do this for whatever reason.
[2]: Example [here](https://xenbits.xenproject.org/docs/4.2-testing/misc/kexec_and_kdump.txt), section 1.a. NB: `DOM0_ARGS` is the Linux kernel cmdline, & `DOM0_IMAGE` is the Linux kernel image. I suggest passing `no-real-mode` (to [the Xen kernel](https://xenbits.xen.org/docs/unstable/misc/xen-command-line.html#no-real-mode-x86)) unconditionally if on x86. If it wasn't obvious, `--append` specifically is not needed & `--command-line` can be used as zfsbootmenu normally does.
[3] 4.14.1 may look like a Linux kernel version number, but it's not. It's the version of the Xen kernel.

**Comment by zdykstra** [comment]
The linked documentation invokes kexec as follows:

`kexec -l --append "no-real-mode" --vmm="/boot/xen.gz" /boot/vmlinuz.gz`

However, with kexec-tools 2.0.23 installed I do not have the `--vmm` option for kexec. I rebuilt kexec-tools with Xen support, and that option isn't present either. Grepping through the source code, the only references I see to `vmm` are in the ia64 tree:

```
$ kexec-tools-2.0.23 > grep -R vmm *
kexec/arch/ia64/kexec-elf-ia64.c:              "    --vmm=FILE            Use FILE as the kernel image for a\n"
kexec/arch/ia64/kexec-elf-ia64.c:       const char *command_line, *ramdisk=0, *vmm=0, *kernel_buf;
kexec/arch/ia64/kexec-elf-ia64.c:               {"vmm",          1, 0, OPT_VMM},
kexec/arch/ia64/kexec-elf-ia64.c:                       vmm = optarg;
kexec/arch/ia64/kexec-elf-ia64.c:       if (vmm)
kexec/arch/ia64/kexec-elf-ia64.c:               kernel_buf = slurp_decompress_file(vmm, &kernel_size);
kexec/arch/ia64/kexec-elf-ia64.c:       if (vmm) {
kexec/arch/ia64/include/arch/options.h: {"vmm",          1, 0, OPT_VMM}
```

Do you have a project source for kexec-tools that supports --vmm on x86_64?

**Comment by 0n-s** [comment]
Whoa, my bad. That documentation is official (& unfortunately the only official one I can find)…but gravely outdated.

Here's the command line I use for booting into Xen:
```
kexec -a -l --module "/boot/vmlinuz-5.15.0-rc7-ns root=ZFS=sli2/ROOT/solidus ro" --module "/boot/initramfs-5.15.0-rc7-ns.img" --command-line "no-real-mode dom0=pvh" /boot/xen-4.14.1.gz
```
This uses the x86 multiboot protocol (documented in `doc/multiboot.html` in kexec-tools repo). Pretty weird thing that seemingly just kexec & GRUB implement, but kexec sets it all up so the details aren't too important.

**Comment by ahesford** [comment]
Xen is interesting, but I think it's too special purpose for a general ZBM implementation. I think your best option would be to use teardown hooks to implement what you want. Teardown hooks are run right before ZBM would kexec into the selected kernel. (Although read-only pools may still be implemented, read-write pools will have been exported; in general, hooks should assume they do *not* have access to a pool, but that doesn't stop the hook from re-importing them if necessary.)

What's missing from hooks is a way to signal what the user has selected. I think we should add some environment variables that tell you what ZBM would like to kexec. These probably amount to
- `ZBM_SELECTED_BE`, which will indicate the ZFS filesystem that holds the BE to boot (*e.g.*, `rpool/environments/myenv`)
- `ZBM_SELECTED_KERNEL`, which will indicate the path to the kernel that would be booted (*e.g.*, `/boot/vmlinuz-5.15.0-rc7-ns`)
- `ZBM_SELECTED_INITRAMFS`, which will indicate the path to the initramfs that goes with the kernel (*e.g.*, `/boot/initramfs-5.15.0-rc7-ns.img`)

Your teardown hook can intercept the normal kexec procedure by loading its own (Xen) kernel and using knowledge about the selected environment to pass the right arguments. Thus, with a teardown hook that has access to these environment variables, the process looks like:
1. Check to see if the pool for the selected BE (which is `${ZBM_SELECTED_BE%%/*}`) is currently imported. If not, import it read-only.
2. Mount `${ZBM_SELECTED_BE}` at some temporary path, then look for `boot/xen*.gz` within that path. If there are multiple matches, use any preferred scheme for selecting one of them.
3. Invoke the `kexec` command as necessary for Xen based on the path to the Xen kernel and the `ZBM_SELECTED_*` environment variables that point to the filesystem and regular kernel/initramfs pair.
4. Jump into the Xen kernel with `kexec --exec` and you will be booting your hypervisor.

If steps 1 or 2 fail, you can always just quit the teardown hook and ZBM will happily continue booting the ordinary kernel. If step 3 fails, you may have replaced the ZBM-loaded kernel with the Xen hypervisor, but that will probably just cause ZBM to print a warning and return to the menu for another attempt. You can even define your own properties to govern the teardown script if you want special behavior for different BEs.

**Comment by ahesford** [comment]
Note: #232 intends to realized my proposed support for Xen-capable teardown hooks.

**Comment by 0n-s** [comment]
That seems fair enough, even if it does make editing the Xen cmdline more difficult at boot time due to the lack of integration. Sure, it's not something that happens often, even if Xen does have some [very useful cmdline options](https://xenbits.xen.org/docs/unstable/misc/xen-command-line.html) that one might want to change depending on the machine (e.g. core_parking or clocksource). But if this solution is better from a maintenance perspective, so be it. It does the job & there are maybe 50 people who use a combination of Xen & ZFS, so it'd be better if this would be a script made in-house for my setup, rather than well-integrated special-cased code that's never tested. :)

**Comment by ahesford** [comment]
Per-machine KCL options for Xen can be stored as arbitrary custom ZFS properties (*e.g.*, `xen:commandline`) that can be parsed by the teardown hook. If you put together a hook to do this, please consider submitting a PR to include it in our `contrib` tree for others to use.

**Comment by HRio** [comment]
@0n-s sorry for bumping this old issue, but was was the kexec cmdline you found to be working from a zfsbootmenu hook script?
