### ISSUE TITLE
Including zdb in the precompiled initramfs

### ISSUE THREAD

**Issue by lciti** [zbm-dev/zfsbootmenu#235]
The [zdb command ](https://zfsonlinux.org/manpages/0.8.4/man8/zdb.8.html) can be very useful to diagnose possible issues with the pools. I wonder if it could be included in the precompiled initramfs so it's available in the zfsbootmenu interactive shell.

**Comment by zdykstra** [comment]
This shouldn't be a problem to do. `zdb` uses the same shared libraries as `zfs` and `zpool`, so it'll just pad the initramfs by a small amount. I'll get this added in to release binaries by the time 1.12.0 is ready.

**Comment by lciti** [comment]
Thanks!

**Comment by zdykstra** [comment]
v1.12.0 will ship with `zdb` and `lsblk` by default. We'll tag a new release in early January, so that we can ship OpenZFS 2.1.2.
