### ISSUE TITLE
[Feature Request] Add plymouth integration for default boot (`zbm.skip`)

### ISSUE THREAD

**Issue by subnut** [zbm-dev/zfsbootmenu#251]
Other OSes (e.g. elementary OS) show the passphrase-entry menu and a spinner, while the laptop manufacturer logo is still visible. IIRC, this was achieved using Plymouth. It'd be nice to have this feature when zfsbootmenu is skipped and the default entry is booted directly (i.e. when `zbm.skip`)

**Comment by zdykstra** [comment]
We currently do not plan on providing support for Plymouth. It greatly complicates the codebase while introducing difficult-to-test features.
