### ISSUE TITLE
`efibootmgr` commands suggested in the README.md don't work.

### ISSUE THREAD

**Issue by subnut** [zbm-dev/zfsbootmenu#252]
Additionally, the `refind_linux.conf` mentioned in the README.md -
```
"Boot Default BE" "ro quiet loglevel=0 timeout=0 root=zfsbootmenu:POOL= spl_hostid="
"Select BE" "ro quiet loglevel=0 timeout=-1 root=zfsbootmenu:POOL= spl_hostid="
```
is very different from the config mentioned [here](https://github.com/zbm-dev/zfsbootmenu/wiki/Void-Linux---Single-disk-UEFI#configure-an-efi-bootloader) -
```
"Boot default"  "zbm.prefer=zroot ro quiet loglevel=0 zbm.skip"
"Boot to menu"  "zbm.prefer=zroot ro quiet loglevel=0 zbm.show"
```

**Comment by subnut** [comment]
Pinging @zbm-dev for comments

**Comment by ahesford** [comment]
I don't have enough information to diagnose the efibootmgr issue. Thanks for pointing out the discrepancy between the README and the wiki page; the syntax from the wiki is preferred, while the README suggests arguments that are now deprecated. We will fix the README shortly.
