### ISSUE TITLE
rd.vconsole.keymap ignored in v1.12

### ISSUE THREAD

**Issue by Soulsuke** [zbm-dev/zfsbootmenu#255]
Hello!

Since 1.12 (due to kernel parameters sanitization I guess) rd.vconsole.keymap is now ignored. Could this be enabled to work again, or is there another supported way to set the keymap without rebuilding zbm?

**Comment by eoli3n** [comment]
I just checked, it still works here.
Here's how I setup it : https://github.com/eoli3n/void-config/blob/master/scripts/install/02-install.sh#L178-L181

**Comment by Soulsuke** [comment]
> I just checked, it still works here. Here's how I setup it : https://github.com/eoli3n/void-config/blob/master/scripts/install/02-install.sh#L178-L181

Isn't that a completely different approach though? It seems to me you're regenerating the efi file with the desired changes, not passing a kernel parameter to the release efi file.

**Comment by ahesford** [comment]
From within ZFSBootMenu, can you drop to a recovery shell with `CTRL+R` and check:
- The contents of `/proc/cmdline` to confirm that your `rd.vconsole.keymap=it` argument appears there;
- The output of `zbmcmdline` also shows the same argument;
- The output of `get_zbm_arg rd.vconsole.keymap` returns `it`.

The last two have nothing to do with how the dracut module sets the keymap, but they will at least confirm that the command line is set properly.

**Comment by Soulsuke** [comment]
>  The contents of `/proc/cmdline` to confirm that your `rd.vconsole.keymap=it` argument appears there;
It does appear correctly

> The output of `zbmcmdline` also shows the same argument;
It appears in here as well, the only difference from the content of the file above is a starting rd.hostonly=0

> - The output of `get_zbm_arg rd.vconsole.keymap` returns `it`.
This one returns "it"

For the record he recovery shell uses a us layout, but `loadkeys it` switches it correctly

**Comment by ahesford** [comment]
I haven't forgotten about this, but real life took all my time this week and I haven't had a chance to work out a solution. I'm afraid the problem may be a change to how we handle the dracut event loop prior to launching ZFSBootMenu and a removal of the explicit console initialization that was done in prior releases.

My plan is to produce a test binary that again explicitly initializes the console to see if that fixes your issue. Please stand by.

**Comment by Soulsuke** [comment]
@ahesford I'll go ahead and say your reply really shows how much you care about your project and its users, which isn't really that common. I really thank you for your support, and although my knowledge of dracut is quite lacking I'll be glad to run other tests and to help however possible (although rl always gets precedence, of course)

**Comment by zdykstra** [comment]
This seems to be resolved! Please let us know if you run into any further issues.
