### ISSUE TITLE
ZFSBootMenu on encrypted removable drive

### ISSUE THREAD

**Issue by PoisonFrog** [zbm-dev/zfsbootmenu#262]
I'm using ZFS on root with ext2 boot partition inside a LUKS volume on a USB drive (Arch Linux), but I would like to migrate to ZFSBootMenu. I'm wondering if it is possible to have GRUB opening the USB partition encrypted with LUKS where the initramfs with ZFSBootMenu is stored?

Is it possible to have ZFSBootMenu on an encrypted drive? I've never used rEFInd so I don't know if it can open encrypted drives like GRUB does or if ZFSBootMenu can work with GRUB.

**Comment by ahesford** [comment]
I don't believe that GRUB plays nicely with ZFSBootMenu. Your best bet is to build a custom ZBM image that includes support for LUKS to unlock the volume that holds your pool. We've had reports of people successfully booting LUKS-encrypted ZFS pools with such configurations in the past.

Nothing about the ZFSBootMenu image needs to be encrypted, so you can put the images on an EFI System Partition, even on another disk if necessary. Our wiki includes directions for booting from an ESP on a USB thumb drive that you should be able to adapt to Arch.

Also, note that you can make the ZBM image a self-contained UEFI executable, which will allow you to skip a loader like rEFInd altogether. Just tell your firmware to boot the ZBM bundle and you're ready to go.

**Comment by PoisonFrog** [comment]
Ohh that's a shame because I would have to give the LUKS headers of my main disk to the initramfs and I prefer to have it behind a passphrase and it doesn't seem to be possible without GRUB support.

**Comment by ahesford** [comment]
You don't have any unencrypted space on the disk? Usually it's a good idea to leave an EFI system partition on a volume and then put the LUKS volume on a partition that fills the rest of the disk.

**Comment by PoisonFrog** [comment]
> You don't have any unencrypted space on the disk? Usually it's a good idea to leave an EFI system partition on a volume and then put the LUKS volume on a partition that fills the rest of the disk.

I don't have any unencrypted space on the disk I have my root pool. I encrypted the entire disk with LUKS. I have an unencrypted EFI partition on a USB drive together with an encrypted /boot partition. The only thing that is unencrypted is the EFI partition. The LUKS header that is necessary to open the main disk is located in the encrypted /boot.

I use GRUB to decrypt the encrypted boot partition that has the initramfs with the LUKS header and the initramfs decrypts the main disk and imports my ZFS pool.

To use ZBM I would have to leave the initramfs unencrypted and that means the header for the main disk would also be exposed.

**Comment by ahesford** [comment]
You can use ZFSBootMenu without exposing secrets in your setup, but it will take a little bit of scripting. ZFSBootMenu supports early hooks that are run before attempting to import any pools. You can write a simple hook that knows how to unlock your `/boot` (which can't be used as `/boot` with ZFSBootMenu, but can be used to store the secrets you need to unlock the device holding your root pool) by prompting for a passphrase, then reading the contents of `/boot` to unlock the LUKS volume. Once your LUKS volume is unlocked by any means, the script can exit and ZFSBootMenu should be able to continue its normal process of importing the pool and booting from it.

We have a simple demo at https://github.com/zbm-dev/zfsbootmenu/blob/master/contrib/luks-unlock.sh which doesn't do quite what you want, but may give you some hints about how you would use an early hook to interact with your LUKS setup.

**Comment by PoisonFrog** [comment]
I see. I was wondering if I can make the grub efi executable load the ZBM initramfs and kernel? It could work like what I am doing now but instead of Grub loading the initramfs and kernel of my installation it would load ZMB's and I would just move my /boot to the default root dataset for ZBM to load it.  Does it work?
