### ISSUE TITLE
[Feature request] Seamless/flicker-free boot with `zbm.timeout=0`

### ISSUE THREAD

**Issue by solbjorn** [zbm-dev/zfsbootmenu#263]
When both the BIOS and the kernel (which is shipped with the binary ZBM builds) support keeping the BIOS vendor splash screen during boot process, transition between BIOS and ZBM kernel initialization is seamless/flicker-free, up to the moment of tearing down the USB controllers.
Then, the splash disappears as "Tearing down devX" is being displayed all the time. Then the host kernel brings BIOS splash back, and it finally transits to the display manager.

I was just curious if it's possible to print those teardown messages only when there's a debug level set in the ZBM command line and do not remove the splash otherwise, so it could stay all the time from the BIOS post and until the DM is launched. WDYT?

**Comment by ahesford** [comment]
I doubt this would work as you expect even if we suppressed the tear-down text. The ZBM kernel will still grab and initialize the console, so you'll instead see a blank screen with a cursor in the upper left.

**Comment by solbjorn** [comment]
Usually the kernel doesn't switch from the splash to the console until something is printed (not counting cursor character).
Hmm, I think I could take one of the ZBM releases which didn't have teardown script embedded and say for sure. I'll post an update soon.

**Comment by zdykstra** [comment]
> Usually the kernel doesn't switch from the splash to the console until something is printed (not counting cursor character).
> I could test some binary build with no teardown messages to double-check (commit https://github.com/zbm-dev/zfsbootmenu/commit/5a5ab0b4d4bda2dd3d2691772d904f720047e94f may've broken it, but anyways).

You can always try setting `console=ttyS0` (or some other device) to keep ZBM from trying to touch tty0. However, there's no promise that this behavior might not change in future releases.

**Comment by solbjorn** [comment]
Wow, works like charm! Bootsplash was still here with no flickering from the BIOS right to the display manager.
Since I already have timeout=0 by default, not an issue at all. When I have some problems, I edit bootmenu's KCL manually.

Thanks!
