### ISSUE TITLE
[feature request] freebsd support

### ISSUE THREAD

**Issue by eoli3n** [zbm-dev/zfsbootmenu#266]
Forth and new lua freebsd bootloader doesn't support custom keymaps, with no plans to...
It doesn't support zfs native encryption yet.

As discussed here, https://github.com/zbm-dev/zfsbootmenu/issues/171, kexec seems to be the limitation to boot freebsd from ZFSBootMenu. I just open the issue to keep it on the table.

@ahesford any news about that old dream ?

**Comment by zdykstra** [comment]
There's been no further developments for `kexec` on x86_64 to support loading a FreeBSD kernel into memory. Until tooling exists that can accomplish this on Linux, this is a dead-end. If you can find/demonstrate a way to kexec into a FreeBSD kernel from Linux, I'll happily provide support for that.
