### ISSUE TITLE
Using systemd for dracut-sshd

### ISSUE THREAD

**Issue by prabirshrestha** [zbm-dev/zfsbootmenu#267]
I would like to use [dracut-sshd](https://github.com/gsauthof/dracut-sshd) but seems like it isn't supported and I get the same error. https://github.com/zbm-dev/zfsbootmenu/issues/81

Are there plans to support systemd? I would like to use OpenSSH server for remote unlock.

**Comment by zdykstra** [comment]
There are no plans to allow systemd in the ZBM initramfs.  For supported  SSH access, please look at [dracut-crypt-ssh](https://github.com/dracut-crypt-ssh/dracut-crypt-ssh) . https://github.com/zbm-dev/zfsbootmenu/wiki/Remote-Access-to-ZBM .

**Comment by ahesford** [comment]
Allowing systemd in the initramfs would bifurcate several key process management functions and require testing that none of the team is in a position to conduct.

**Comment by prabirshrestha** [comment]
I have moved to using dropbear and have been successfully able to unlock and start the OS. Here is the [script](https://github.com/prabirshrestha/simple-ubuntu-installer/blob/3590be259bd65c63b86c4b21b2a51c7fe4ddefc4/simple-ubuntu-installer#L283-L296) 

The problem is it asks me for password twice hence I had to enable crypt-ssh in `etc/zfsbootmenu/dracut.conf.d/dropbear.conf` as well as `/etc/dracut.conf.d/dropbear.conf` as shown below.

![image](https://user-images.githubusercontent.com/287744/156278321-2ca406b5-31e4-47ea-8ad7-160df4de11b9.png)

For the first one I use ssh and run `zfsbootmenu` which allows me to unlock. Then I need to ssh again but this time since it is passed zfsbootmenu, I need to run `systemd-tty-ask-password-agent`.

![image](https://user-images.githubusercontent.com/287744/156278902-3ee09ceb-495e-447c-9179-bd93478cafb5.png)

Is this expected? I was hoping I need to ssh only once and type the password only once.

I even tried adding saving the password in `/etc/zfs/zroot.key` with `000` permission and then use `zfs change-key -o keylocation=file:///etc/zfs/zroot.key -o keyformat=passphrase zroot` but this leads to more droping into emergency shell as the key cannot be loaded. I was hoping the initial zfs would unlock it and then on the second password ask it would load from the disk hence not requiring second password and ssh at all.

**Comment by prabirshrestha** [comment]
Thanks for all the quick suggestions. Made the appropriate changes and seems to work now with single password.

https://github.com/prabirshrestha/simple-ubuntu-installer/pull/1

It will be good to update the https://github.com/zbm-dev/zfsbootmenu/wiki/Remote-Access-to-ZBM to include those suggestions on making sure to add key to the encrypted system initramfs.
