### ISSUE TITLE
Where do I put `options zfs` ?

### ISSUE THREAD

**Issue by rubaboo** [zbm-dev/zfsbootmenu#278]
Could you please clarify. [Overview of the Boot Process](https://zfsbootmenu.org/) says 

> After a boot environment is selected for boot (automatically or manually), load the selected kernel and initramfs, unmount all ZFS filesystems, and boot the system.

That sounds like setting `zfs_arc_(min|max)` via `/etc/modprobe.d/zfs.conf` and `update-initramfs` in the "root-on-zfs" OS should work. But it doesn't, not for me anyways. Also, the [Readme](https://github.com/zbm-dev/zfsbootmenu#command-line-arguments) here seems to imply the parameter should be set via zfsbootmenu KCL. Is that the only way it would work?

**Comment by ahesford** [comment]
I believe setting them in a `modprobe.d` configuration file should work. Are you sure that you regenerates the initramfs for the kernel you're actually booting?

If you want to set this parameter on the command line instead, you can add it to the `org.zfsbootmenu:commandline` property. On the command line, the properties may have to be prefixed with `zfs.`, *e.g.*, `zfs.zfs_arc_max`.

**Comment by zdykstra** [comment]
Dracut will only add `/etc/modprobe.d/*.conf` files to an initramfs if you build in `hostonly` mode. Otherwise it always pulls in files from `/lib/modprobe.d/*.conf` regardless of the build mode.
