### ISSUE TITLE
Document how to load EFI binary on USB for recovery

### ISSUE THREAD

**Issue by Jip-Hop** [zbm-dev/zfsbootmenu#279]
After following the [Debian installation instructions](https://github.com/zbm-dev/zfsbootmenu/wiki/Debian-Bullseye-installation-with-ESP-on-the-zpool-disk) my system wouldn't boot. So I tried to load the EFI binary from the [Releases](https://github.com/zbm-dev/zfsbootmenu/releases) page on a USB stick, but didn't find instructions on how to do it. I found hints inside [CHANGELOG.md](https://github.com/zbm-dev/zfsbootmenu/blob/master/CHANGELOG.md#binary-release-for-x86_64) and later found more advice inside https://github.com/zbm-dev/zfsbootmenu/issues/265#issuecomment-1059746259. But still additional documentation on how to prepare the USB stick would be great 🙂 

Here are my notes on how to accomplish it:

Download latest release, e.g. `zfsbootmenu-recovery-vmlinuz-x86_64-v1.12.0.EFI`.

On MacOS make an `EFI` partition by formatting the USB as `HFS+`. Yes, this seems strange... but formatting as `HFS+` will automatically make a ~200MB `EFI` partition at the start of the disk. Just format the USB stick with Disk Utility with GUID partition scheme. Then run `diskutil list` in the terminal and find the IDENTIFIER for the `EFI` partition. Mount with `sudo diskutil mount disk2s1` (replace `disk2s1` with identifier from previous step).

Make an `EFI` directory with `boot` directory inside. Rename the downloaded `EFI` binary to `bootx64.efi` and move inside `boot`. Result: `/EFI/boot/bootx64.efi`.

My Fujitsu D3644-B will now boot to zfsbootmanager from the USB stick! And I can finally boot into Debian :D

**Comment by Jip-Hop** [comment]
Turns out it's much easier. I just had to format the USB stick as FAT32 with GUID partition scheme. Then rename zfsbootmenu-recovery-vmlinuz-x86_64-v1.12.0.EFI to bootx64.efi and put it on the USB stick at /EFI/boot/bootx64.efi.

**Comment by ahesford** [comment]
`\EFI\boot\bootx64.efi` tends to work because most EFI implementations look there by default. You can probably also call it anything you like and tell your firmware to look in the right place. (Some firmware offers a nice UI for selecting the file to boot. For others, like Macs, you'll need to use `efibootmgr` to set the right values.)

**Comment by jrtoddy** [comment]
@ahesford I've been playing about with this sort of thing - if you'd like, assign this to me and I'll draft up a little addition to the wiki. :+1:

@Jip-Hop Glad you found it helpful. :+1:

**Comment by jrtoddy** [comment]
@Jip-Hop I have added a little entry to the [wiki](https://github.com/zbm-dev/zfsbootmenu/wiki/Portable-ZFSBootMenu), let me know if you think people will find it helpful. :smile:

**Comment by Jip-Hop** [comment]
Thanks for making the wiki! I've added a little note, I hope you don't mind :)
