### ISSUE TITLE
Which pool's `org.zfsbootmenu:commandline` is taken when BE consists of more than one pool?

### ISSUE THREAD

**Issue by rubaboo** [zbm-dev/zfsbootmenu#280]
I have `bpool` (mounted at `/boot`) and `rpool` (`/`), for example -- the result of following [OpenZFS documentation](https://openzfs.github.io/openzfs-docs/Getting%20Started/Debian/Debian%20Bullseye%20Root%20on%20ZFS.html). It seems reasonable to assume that [ZFS Properties](https://github.com/zbm-dev/zfsbootmenu/blob/master/docs/pod/zfsbootmenu.7.pod#zfs-properties) are only being read from the root pool, but I did not see this mentioned explicitly anywhere. Can you confirm?

**Comment by ahesford** [comment]
ZFSBootMenu [will not work with this configuration](https://github.com/zbm-dev/zfsbootmenu/blob/master/docs/BOOTENVS.md).

The documentation you link (which, while hosted by OpenZFS, is written by a third party) suggests that a separate pool be used to house a `/boot` filesystem as a kludge to accommodate the crippled ZFS support in GRUB. This is a terrible arrangement that only leads to problems. (You're better off putting `/boot` on an ext4 partition with GRUB, but that won't be recognized by ZFSBootMenu.)

The `org.zfsbootmenu:commandline` property is read from the root filesystem (which must contain `/boot` and its contents). Of course, ZFS property inheritance applies here, so you can also set the property on a parent of the root filesystem. You can also use our [purpose-built `%{parent}` expansion](https://github.com/zbm-dev/zfsbootmenu/blob/master/docs/pod/zfsbootmenu.7.pod#zfs-properties) to define common properties on a parent and add additional, specific options on each root filesystem.
