### ISSUE TITLE
support initramfs thats generated by booster

### ISSUE THREAD

**Issue by Dragon-debian** [zbm-dev/zfsbootmenu#281]
There is an alternative initramfs generator for arch linux, called `booster`.
this one, saves generated initramfs as `booster-${label}.img`.
its nice to find initrams with this names.
[This is](https://wiki.archlinux.org/title/Booster) the related page on arch wiki

**Comment by zdykstra** [comment]
Based on the documentation, I believe https://github.com/zbm-dev/zfsbootmenu/commit/86815464068efaf2a3fd2c3fde1e5f76066c5033 is sufficient to support booster. You can find EFI and component builds of that commit at https://github.com/zbm-dev/zfsbootmenu/actions/runs/2010162821 . Can you test one locally, if you have Booster installed already?

**Comment by Dragon-debian** [comment]
I booted the linux image and initramfs on a legacy system with syslinux and it worked.

I renamed a void kernel image and intramfs and it worked again.
The [BOOTENVS.md](https://github.com/zbm-dev/zfsbootmenu/blob/master/docs/BOOTENVS.md) needs an update to reflect new change.

**Comment by zdykstra** [comment]
That's an insufficient test. Does an initramfs generated by `booster` actually boot a root-on-ZFS system? Until that's demonstrated to be working, There's no point in adding support for that initramfs generator.

**Comment by Dragon-debian** [comment]
I did some searches and it seems that booster doesnt support root-on-zfs yet. so as you said, its pointless to add support for it.
https://github.com/anatol/booster/issues/33

**Comment by zdykstra** [comment]
This can be added in once booster adds support for ZFS.

**Comment by leonghui** [comment]
To update, booster can detect ZFS since [version 0.9](https://github.com/anatol/booster/releases/tag/0.9) but native encryption is not supported yet, see https://github.com/anatol/booster/issues/191.
