### ISSUE TITLE
changin kcl in BE menu, changes all kcls

### ISSUE THREAD

**Issue by Dragon-debian** [zbm-dev/zfsbootmenu#289]
changing the kernel command line of a boot environment in BE menu, changes all kcls of different boot environments.

for example there is a pool called `zroot` with three seprate BEs:
```
zroot/ROOT/BE1  kcl: rw quiet splash
zroot/ROOT/BE2  kcl: rw loglevel=7 zfs.zfs_arc_max=536870912
zroot/ROOT/BE3  kcl: rw spl.spl_hostid=0x8d76ca0b
```
If someone presses `CTRL + E` in BE menu and changes the second kcl to `rw loglevel=4`, all other kcls became `rw loglevel=4`.

**Comment by zdykstra** [comment]
Changing it through that mechanism is temporary, so it's meant to be used for a single boot of a single environment.

**Comment by Dragon-debian** [comment]
Mabe someone changes a kcl and then realizes that it was the wrong BE, now he or she has to rewrite the correct kcl for the correct BE from the beginning.

I think it should only change the kcl of the selected BE.

As far as I understood, by changing the kcl in BE menu, a file with name of `cmdline` is created in `"${BASE}"` dir (usally /zfsbootmenu) and its content is used for kcls of all BEs.

I think we can store the original kcl of each BE in `"${BASE}/${fs}/cmdline.orig"` and copy its content to `"${BASE}/${fs}/cmdline"` to use it later. And changin the kcl from BE menu, should change the content of `"${BASE}/${fs}/cmdline"`.

This way its possiable to add a key binding (e.g. `MOD + X`) later, to rest the kcl to the default value.

**Comment by zdykstra** [comment]
That's a level of complexity that we're not interested in supporting right now. However, I have added an option to revert a modified KCL if you've accidentally edited the wrong one.

https://github.com/zbm-dev/zfsbootmenu/commit/65dd0cd2180af9f0b370ad39bde79d89e7fad327
