### ISSUE TITLE
UEFI installation always fail

### ISSUE THREAD

**Issue by bobblkabb** [zbm-dev/zfsbootmenu#295]
I have already worked through the [instructions](https://github.com/zbm-dev/zfsbootmenu/wiki/Void-Linux---Single-disk-UEFI) on 3 computers, point by point and always the encrypted version.
None of the installations worked.
At the point refind-install (I had chosen the pre-build zfsbootmenu variant) I got efi variable error messages. I then ran efivar-tester which claimed that the device was not UEFI capable.
The first two laptops have a CSM option in the bios, so I assumed that they are UEFI capable. And the third laptop (Chromebook Acer C720 with Coreboot) there is even a UEFI shell.
In this respect, I must have made a mistake when installing according to instructions. What could I have done wrong.

**Comment by Dragon-debian** [comment]
If the laptop is booted in UEFI mode, there should be some files in this directory.
```
/sys/firmware/efi/efivars/
```

**Comment by ahesford** [comment]
Again, this is a topic for the discussions. Please open a topic there if you like. If you identify a specific defect with the instructions or the ZBM logic, open an issue here.

**Comment by bobblkabb** [comment]
I'm sorry, wasn't aware of 'discussions'. You can delete this Issue. I moved it.
