### ISSUE TITLE
read-only examples

### ISSUE THREAD

**Issue by mfiano** [zbm-dev/zfsbootmenu#299]
Forgive me for asking a probably very obvious question. I just started using ZFS on Arch Linux after years of BE management on FreeBSD. I'm curious why the examples in the README set the boot environments to be mounted as read-only. I'm not sure what best practice is here, but currently I do not have any BE's aside my default `zroot/ROOT/default` dataset, which I expect to be able to load read-write. Infact, I have systemd mount units that attempt to mount remote filesystems and fail because of this. Can you please detail the reasoning for the examples using `ro`, and outline a best practice for being able to boot my default BE normally, if there is an obvious reason I'm not seeing for mounting everything read-only. Thank you :)

**Comment by ahesford** [comment]
The examples use `ro` for the ZFSBootMenu image but generally omit any arguments for the finals boot environment.

I think the issue you have is that the Arch initramfs defaults to read-only mounts of ZFS roots unless the kernel command line explicitly includes an `rw` argument. Whatever you've added to the`org.zfsbootmenu:commandline` property (whether it comes from `zroot`, `zroot/ROOT` or `zroot/ROOT/default`), add an `rw` option to the list. If you haven't set this property anywhere, the default is `quiet loglevel=4`.

**Comment by mfiano** [comment]
The issue actually isn't the loader's use of `ro`. It's the dataset property not having `rw`. Adding the latter fixed it for me. (Adding it to the former did nothing).
