### ISSUE TITLE
unable to set default kernel

### ISSUE THREAD

**Issue by popcorn9499** [zbm-dev/zfsbootmenu#326]
in zfs boot menu I am unable to set a default kernel with the menu and it refuses to let it stick even to the next menu changing from /boot/vmlinuz-linux-lts to /boot/vmlinuz-linux.

versions.
zfsbootmenu:2.0
zfs version: 2.1.5-1 on archlinux

**Comment by ahesford** [comment]
Ah, another casualty of Arch's lack of kernel versions. I suspect you can set the `org.zfsbootmenu:kernel` property to `vmlinuz$` to get it to match, because ZBM selection just uses built-in bash regex matching.
