### ISSUE TITLE
Native encryption and zfs-mount-generator

### ISSUE THREAD

**Issue by ReneHollander** [zbm-dev/zfsbootmenu#327]
I followed https://github.com/zbm-dev/zfsbootmenu#native-encryption to setup native encryption and to avoid having to type the passphrase twice.

After typing the passphrase once, pressing enter, pressing enter again to boot from the selected root dataset, systemd gets very sad: 
![image](https://user-images.githubusercontent.com/5379596/182920508-c5f93b26-33f3-48c1-a2ad-c3b1bec5746d.png)

Updating the kernel command like and adding `systemd.mask=etc-zfs-keys.mount` allows me to boot the system and skipping mounting of `/etc/zfs/keys/`.

It seems that when using zfs-mount-generator cyclic systemd units are generated:
![image](https://user-images.githubusercontent.com/5379596/182921090-1d1ae878-8536-4705-8bf3-c3c82e53a725.png)

Looking at https://manpages.debian.org/unstable/zfsutils-linux/zfs-mount-generator.8.en.html I can't find a feature that lets me disable generating and using `zfs-load-key@rpool.service`. `systemd.mask=zfs-load-key@rpool.service` causes the system to become unbootable (I guess because of the BindsTo in the unit file). Is there any other trick to work around the issue?

Some extra info:
- Using ZFSBootMenu v2.0.0
- Fresh Arch install (I have an Ansible playbook rebuilding the system inbetween my different attempts at fixing my issues getting ZFS on Root working)
- zfs-list.cache/rpool:
  ![image](https://user-images.githubusercontent.com/5379596/182922599-85b1e80c-6bfc-482c-8d39-f72fe8bdd592.png)

**Comment by ahesford** [comment]
I don't know much about how systemd plays with ZFS in initramfs images. I also don't know how systemd is creating these units. Is it reading `/etc/fstab`? If so, what does that file look like? In principle, you shouldn't need to mount `/etc/zfs/keys` to import your pool at all, because the initramfs should handle unlocking and mounting the root filesystem, and the keys should be copied into your initramfs image. (Be careful using `mkinitcpio` and trying to put keys into your initramfs image on Arch, because `mkinitcpio` doesn't set a restrictive umask by default and anybody with read permission for your initramfs image will be able to read out your pool keys. Dracut explicitly sets a umask of 0077 and Void Linux manually sets the same umask in the hook that calls `mkinitcpio` to avoid this problem.) When your keys are copied into the initramfs, you only need to have `/etc/zfs/keys` mounted when you regenerate the initramfs, but this can happen much later at boot.

**Comment by ReneHollander** [comment]
> I don't know much about how systemd plays with ZFS in initramfs images. I also don't know how systemd is creating these units. Is it reading `/etc/fstab`? If so, what does that file look like?

There is a zed script running that writes the `/etc/zfs/zfs-list.cache/rpool` shown above every time the datasets change (e.g `zfs set mountpoint` is executed). Then during boot https://github.com/openzfs/zfs/blob/master/etc/systemd/system-generators/zfs-mount-generator.c is executed by systemd to generate the unit files based on whats in `/etc/zfs/zfs-list.cache/rpool`. These unit files are shown above.

> In principle, you shouldn't need to mount `/etc/zfs/keys` to import your pool at all, because the initramfs should handle unlocking and mounting the root filesystem, and the keys should be copied into your initramfs image.

> When your keys are copied into the initramfs, you only need to have `/etc/zfs/keys` mounted when you regenerate the initramfs, but this can happen much later at boot.

The pool is importing fine with the keys in the initramfs. The issue is once systemd starts mounting all the other datasets based on the generated systemd units, which also again try to unlock the pool. The issue in detail is that systemd needs wants to mount `/etc/zfs/keys`, but first tries to unlock, and for that systemd expects `/etc/zfs/keys` to be mounted.

> (Be careful using `mkinitcpio` and trying to put keys into your initramfs image on Arch, because `mkinitcpio` doesn't set a restrictive umask by default and anybody with read permission for your initramfs image will be able to read out your pool keys. Dracut explicitly sets a umask of 0077 and Void Linux manually sets the same umask in the hook that calls `mkinitcpio` to avoid this problem.)

Good to know, thanks. Will see if I can figure out how to fix this.

---

So it seems like something is needed in https://github.com/openzfs/zfs/blob/master/etc/systemd/system-generators/zfs-mount-generator.c to be able to ignore generating unit files for unlocking certain pools.

**Comment by ahesford** [comment]
I would disable the mount unit generator, if possible. I think OpenZFS ships a systemd unit that effectively just does `zfs mount -al` to use the normal ZFS mounting logic rather than relying on systemd dependency resolution. Does the use of systemd mount units buy you anything?

**Comment by ReneHollander** [comment]
I think I found a viable workaround when using zfs-mount-generator by overriding the unit file that tries to load the keys:
For example for the pool `rpool`:

Create a copy of the unit file with `systemctl edit zfs-load-key@rpool.service --full` and update the contents as follows:
- Remove `RequiresMountsFor`. This will ensure systemd won't add a circular dependency.
- Change `ExecStart=/bin/sh -euc '[ "$$(/usr/bin/zfs get -H -o value keystatus "rpool")" = "available" ]'`. This will now only verify the encryption key is loaded
- Change `ExecStop=/bin/true`: Not sure if necessary. Might help against loosing the encryption key in case you mess with the units by mistake.

End result for me:
```
[Unit]
Description=Load ZFS key for rpool (OVERRIDDEN - DOES NOTHING)
DefaultDependencies=no
Wants=
After=

[Service]
Type=oneshot
RemainAfterExit=yes
StandardOutput=null
StandardError=null
ExecStart=/bin/sh -euc '[ "$$(/usr/bin/zfs get -H -o value keystatus "rpool")" = "available" ]'
ExecStop=/bin/true
```

Unfortunately systemd doesn't allow partial overrides (using a override.conf) to remove dependencies. As such a full copy of the unit needs to be made.

**Comment by ReneHollander** [comment]
@ahesford, do you think it is worth explaining this in the Readme? If so I can send a PR. If not feel free to close this issue.

Thanks for your help!

> (Be careful using mkinitcpio and trying to put keys into your initramfs image on Arch, because mkinitcpio doesn't set a restrictive umask by default and anybody with read permission for your initramfs image will be able to read out your pool keys. Dracut explicitly sets a umask of 0077 and Void Linux manually sets the same umask in the hook that calls mkinitcpio to avoid this problem.)

Seems this was fixed in https://github.com/archlinux/mkinitcpio/commit/49c17915d28b371e635688521f127f13447f04c3? My initramfs images have permissions of `-rw-------`.

**Comment by ahesford** [comment]
You're right, looks like they solved the umask problem.

Although the issue you've encountered isn't particular to ZBM and is also too Arch-specific to merit inclusion in the README, feel free to create a [wiki page](https://github.com/zbm-dev/zfsbootmenu/wiki) describing the issue and your resolution. Alternatively, a full adaptation of the Void guide to Arch would be welcome.
