### ISSUE TITLE
Compatability with zectl

### ISSUE THREAD

**Issue by jose-pr** [zbm-dev/zfsbootmenu#329]
Trying to make this work with a os that uses zectl (truenas scale) , are there any plans to offer a zectl plugin that works for zfsbootmenu?

**Comment by zdykstra** [comment]
There are currently no plans to offer integrations with [zectl](https://github.com/johnramsden/zectl). Realistically, ZFSBootMenu doesn't need integrations with other tools. It is self-contained and discovers everything needed on each boot (and each time it actually displays a menu/screen). Tools such as `beadm` from FreeBSD are generally better suited to use with ZFSBootMenu.

**Comment by ahesford** [comment]
ZFSBootMenu chooses its default boot environment by reading the `bootfs` property of your pool. If there are multiple pools defined, it will tend to favor the pool listed first in the output of `zpool list` unless you boot ZFSBootMenu with the `zbm.prefer=<pool>` kernel command line, in which case that will be favored. If `bootfs` is undefined, you'll get the menu to choose among the environments that ZBM can find. Just set `bootfs` to whatever you like to influence the default behavior of ZBM.
