### ISSUE TITLE
Using zfsbootmenu breaks my laptop's touchpad (fixed)

### ISSUE THREAD

**Issue by alaricljs** [zbm-dev/zfsbootmenu#347]
Problem:  using zfsbootmenu breaks the touchpad on my laptop (HP Omen 16 2022)

Symptoms:
Booting via zfsbootmenu results in this 1 logged error:
`kernel: i2c_designware AMDI0010:03: Unknown Synopsys component type: 0xffffffff`

This prevents i2c-designware-pci from attaching properly to the device and providing the interface that subsequently connects to the touchpad via the i2c_hid_acpi driver.

The touchpad does not work.  Booting directly (via grub,  USB live image, ...) the touchpad works.

Solution:
For kernels with this driver built-in (not a module) - includes Arch.
`initcall_blacklist=dw_i2c_init_driver,dw_i2c_driver_init`  needs to be added to the zbm kernel options that are set using efibootmgr 

For kernels where the designware i2c driver is a module use (untested!!):
`i2c_designware_pci.blacklist=yes`  needs to be added

**Comment by zdykstra** [comment]
A user-editable Wiki to help collect small things like this is probably called for. I'll try to get a basic page outline created for this.

**Comment by ahesford** [comment]
Closing because this is a client-side configuration issue. Setting the right KCL with `efibootmgr`, rEFInd or other intermediate loader, or editing the embedded KCL with [`zbm-efi-kcl`](https://github.com/zbm-dev/zfsbootmenu/blob/master/bin/zbm-efi-kcl) will accomplish what you need.

**Comment by zdykstra** [comment]
I've added a very basic initial wiki page at https://github.com/zbm-dev/zfsbootmenu/wiki/Fixes-for-specific-hardware . Feel free to modify the layout if you're so inclined.
