### ISSUE TITLE
Keyboard shortcuts at bottom of top menu screen 

### ISSUE THREAD

**Issue by Sithuk** [zbm-dev/zfsbootmenu#350]
The zfsbootmenu menu screen used to provide a more extensive list of helpful shortcuts at the bottom, including to snapshots and kernel selection. Now I only see:
[RETURN] boot
[CTRL+R] recovery shell
[CTRL+H] help

CTRL+S and CTRL+K still work, but I don't have the helpful shortcut summary at the bottom, so the issue is just a UI one.

I also have a little yellow ! at the top left that may be related? Is there anyway to get the larger list of shortcuts back?

![zfsbootmenu_v2](https://user-images.githubusercontent.com/48687737/198869197-94794fdf-a8b5-4222-b759-3f89e3091f2e.JPG)

**Comment by ahesford** [comment]
You need the `column` program available, which in Debian and Ubuntu should be part of the `bsdextrautils` package.
