### ISSUE TITLE
Diff Viewer can leave a dangling filesystem mount

### ISSUE THREAD

**Issue by zdykstra** [zbm-dev/zfsbootmenu#357]
Hitting ctrl-c on the diff viewer screen can cause the filesystem to remain unmounted after control returns to the `draw_snapshots` function. Possibly trap `SIGINT` so that the filesystem is always unmounted?

**Comment by ahesford** [comment]
Now that we've isolated all mounts that we control under `$BASE/environments`, how about just walking the tree and I mounting anything in there at the top of the ZBM event loop?

**Comment by zdykstra** [comment]
That's probably a good idea to do in general. That won't be completely sufficient for this case though, since the [diff viewer](https://github.com/zbm-dev/zfsbootmenu/blob/master/zfsbootmenu/lib/zfsbootmenu-lib.sh#L276-L278) is executed as an alternate screen for the Snapshots `fzf` instance. So if you diff two snapshots, go back and a mount sticks, you won't be able to pick two new snapshots and diff them.

I'm not able to reproduce (reliably or otherwise) the lingering mount from the diff viewer.  We could paper over the issue by having `mount_zfs` just check the `mounted` property and return true if it's already mounted, then clean up mounts in tthe ZBM event loop.  The other option is to add a few traps to `draw_diff` so that no matter what, the filesystem is unmounted. It should be safe to install traps however we want there, since the `zfunc` wrapper script is the only tool that calls `draw_diff`.

**Comment by zdykstra** [comment]
I found a repeatable test case for this. When `zfs diff` blocks, and a double ctrl-c is issued, `fzf` and then `zfunc` are killed in that order, causing the `umount` to either fail or never be reached.

Since `draw_diff` is now called as an `execute[]` keybind for the Snapshot fzf instance, the entire `draw_diff` function should be moved to a libexec helper where SIGINT can be gracefully trapped.
