### ISSUE TITLE
ZFS encryption passphrase is exposed in plaintext

### ISSUE THREAD

**Issue by PanCakeConnaisseur** [zbm-dev/zfsbootmenu#374]
AFAICS the encryption passphrase is stored in plaintext to the initrd and thus trivially readable from etc/zfs/zroot.key using

```bash
lsinitrd -f /etc/zfs/zroot.key
```
This is configured in the [Dracut setup ](https://github.com/zbm-dev/zfsbootmenu/wiki/Void-Linux---Single-disk-UEFI#configure-dracut-to-load-zfs-support) of the _Void Linux Single disk UEFI_ guide. Unless I am missing something, this is a massive security problem.

**Comment by ahesford** [comment]
Dracut does the right thing and sets mode 600 on the initramfs. I think the same is true for mkinitcpio as of version 31. (It's certainly true on the mkinitcpio master branch.)

**Comment by PanCakeConnaisseur** [comment]
But isn't the initramfs stored on boot/efi/EFI/void and thus accessible without any password?

**Comment by zdykstra** [comment]
> But isn't the initramfs stored on boot/efi/EFI/void which is unencrypted and thus accessible without any password?

The OS's initramfs is stored in `/boot`, which is encrypted. ZFSBootMenu's initramfs/EFI is stored on your ESP - it does not contain a passphrase.

**Comment by PanCakeConnaisseur** [comment]
I wasn't aware of this difference. Thank you for clearing this up.
