### ISSUE TITLE
Fedora 37 - Out of space on LiveCD

### ISSUE THREAD

**Issue by Anonymo** [zbm-dev/zfsbootmenu#399]
After doing the step:

dnf install -y zfs

DNF wants to install 200+ dependencies and the liveCD space runs out.

**Comment by zdykstra** [comment]
How much RAM do you have in the machine?

**Comment by Anonymo** [comment]
> How much RAM do you have in the machine?

16 GB but I don't think it's about RAM but some sort of livecd virtual space.
I know the command to do it on arch to Increase cowspace partition: mount -o remount,size=2G /run/archiso/cowspace

![IMG_0343](https://user-images.githubusercontent.com/967787/211716299-b375b1f0-5813-4ca3-82a4-8d9486590a4d.jpg)

**Comment by Anonymo** [comment]
Might be something like: 
# mount -o remount,size=4G,noatime /tmp

Going to try it.

**Comment by zdykstra** [comment]
What's the output of `df -h` on this machine? I just booted the Fedora Live ISO via the latest release of Ventoy and `/dev/mapper/live-rw` has is 7.4GB with 2.0GB free after booting into the live desktop. 

I'm able to successfully run https://docs.zfsbootmenu.org/en/latest/guides/fedora/uefi.html#install-updated-zfs-packages and install ZFS 2.1.7 on the live environment.

With ZFS installed:

```
[root@localhost-live ~]# df -h
Filesystem           Size  Used Avail Use% Mounted on
devtmpfs             4.0M     0  4.0M   0% /dev
tmpfs                 12G     0   12G   0% /dev/shm
tmpfs                4.7G  9.8M  4.7G   1% /run
/dev/ventoy          1.9G  1.9G     0 100% /run/initramfs/live
/dev/mapper/live-rw  7.4G  6.3G  1.2G  85% /
tmpfs                 12G   40K   12G   1% /tmp
vartmp                12G     0   12G   0% /var/tmp
tmpfs                2.4G  160K  2.4G   1% /run/user/1000
```

**Comment by Anonymo** [comment]
> Directly booting the ISO linked in the guide shows the same behavior. / is 7.4GB with 2.0GB free. 

Could it be that it's because I'm using the KDE spin?

![IMG_0343](https://user-images.githubusercontent.com/967787/211722295-d7957950-8454-4f38-8345-3f7a83fec5d7.jpg)

**Comment by zdykstra** [comment]
That's exactly what's happening; the KDE spin appears to take up more space by default.  

```
[root@localhost-live ~]# rpm -qa --queryformat '%{SIZE} %{NAME} \n' | sort -n -r | head -20
305098599 libreoffice-core 
243174531 firefox 
228401031 glibc-all-langpacks 
203235352 java-17-openjdk-headless 
192230752 linux-firmware 
133970181 google-noto-sans-cjk-ttc-fonts 
116753211 ibus 
114465912 llvm-libs 
96839813 kernel-core 
96579415 cldr-emoji-annotation 
95315682 gcc 
77773749 mesa-dri-drivers 
62712603 geolite2-city 
59205608 kernel-modules 
55757342 webkit2gtk4.1 
55694206 webkit2gtk5.0 
53517945 firefox-langpacks 
52738073 gnome-user-docs 
51446292 libpinyin-data 
46624902 iwlax2xx-firmware 
```

I then ran the following:

```
rpm -e --nodeps google-noto-sans-cjk-ttc-fonts linux-firmware java-17-openjdk-headless libreoffice-core
```

Removing those packages brought me up to 2.7GB free - a gain of 700MB.  Based on the space fluctuations I was seeing, you'll need about 1.2 to 1.3GB of space free to install ZFS on the Live CD.

**Comment by Anonymo** [comment]
@zdykstra Zach, thank you so much for your help, even going out of your way to replicate my setup.  Going to sleep ATM, but will try the setup tomorrow.

**Comment by Anonymo** [comment]
Looks like it worked.  Unfortunately, the spins don't do a post-setup for creating a user like the main GNOME one does, so I need to run through it again and add a user before I exit the installation and reboot.

**Comment by ahesford** [comment]
Don't run through it again! Just use the "jump to chroot" option in ZBM to fix up your installation. Select the boot environment in the menu, `Ctrl+W` to reimport the pool read/write, then `Ctrl+J` to jump into the installation. Fix up what you need, exit and boot.

**Comment by Anonymo** [comment]
> Don't run through it again! Just use the "jump to chroot" option in ZBM to fix up your installation. Select the boot environment in the menu, `Ctrl+W` to reimport the pool read/write, then `Ctrl+J` to jump into the installation. Fix up what you need, exit and boot.

@ahesford thanks Andrew.  If I want to install the KDE spin on another PC, where would be the recommended step to install the user fall on?
