### ISSUE TITLE
Provide image with zfs from GIT (for those that needs RefLinks and/or Early ZSTD Abort)

### ISSUE THREAD

**Issue by isopix** [zbm-dev/zfsbootmenu#404]
Please provide image with zfs from GIT (for those that needs RefLinks and/or Early ZSTD Abort) for a while.

I know that normally people prefer stable releases, but ReflInks and ZSTD Early Abort are so useful features with huge demand, that even [archzfs] provides both (stable) 'zfs-dkms'/'zfs-utils' and unstable 'zfs-dkms-git'/'zfs-utils-git' combo, that are updated every 1-2 weeks, because there are many ArchLinux ZFS users that prefers that.

Except fragmentation/performance lack of reflinks was main reason for many to choose XFS over ZFS, because it can save tons of storage space in many usecases (VMs cloning, etc). Can be also utilized for offline deduplication.

Lack of 'early abort' for ZSTD was main reason that many stayed with LZ4, but ZSTD provides better compression ratio at same speed (especially at larger block sizes

It would be temporal situation, because in few months this features will be probably merged.

**Comment by zdykstra** [comment]
ZFSBootMenu can simply be built on your local machine and it will use your local copy of ZFS. We will not be doing official releases on a weekly basis to include unreleased ZFS versions.
