### ISSUE TITLE
Non-US keymaps don't seem to work with recovery shell

### ISSUE THREAD

**Issue by Mastergatto** [zbm-dev/zfsbootmenu#410]
This is an issue similar to #255.

I'm on archlinux and I have used mkinitcpio to generate the EFI image. I have appended rd.vconsole.keymap parameter in the UEFI entry.  ZBM version is 2.1.0, installed from AUR.

I can confirm that the argument is passed successfully by checking `/proc/cmdline` and `zbmcmdline` that both have it. Also `get_zbm_arg rd.vconsole.keymap` is currently set with the value given by me.

Unlike the reporter of #255 , it seems that I'm unable to launch loadkeys.

**Comment by zdykstra** [comment]
Please ensure that you're using the `keymap` hook in the ZFSBootMenu initcpio configuration. It will parse `/etc/`vconsole.conf` and add add/set your systems keymap in the initramfs.

**Comment by Mastergatto** [comment]
Thank you, it has worked. May I suggest to add it in the ZBM initcpio configuration by default? Or at least document it in the file?
