### ISSUE TITLE
2.1.0, Debian, single disk, Unencrypted, rEFInd, missing /etc/mtab

### ISSUE THREAD

**Issue by HankB** [zbm-dev/zfsbootmenu#414]
Following instructions at <https://docs.zfsbootmenu.org/en/latest/guides/debian/uefi.html#configure-efi-boot-entries>

`refind-install` and `apt install` both report errors involving missing `/etc/mtab` and this results in a non-booting installation. I checked the instructions at step 4 section 5 <https://openzfs.github.io/openzfs-docs/Getting%20Started/Debian/Debian%20Bullseye%20Root%20on%20ZFS.html#step-4-system-configuration> and see the command

```text
ln -s /proc/self/mounts /etc/mtab
```

I booted live media, `chroot`ed into the install and performed this step followed by `refind-install` and this resulted in a bootable system.

Hardware is an ancient MacBook5,1 and I was using `debian-live-11.6.0-amd64-gnome+nonfree.iso` install media on a USB Thumb drive (Using Ventoy to boot the media.)

Relevant output while running the rEFInd install commands was

```text
...
Installing rEFInd to the ESP...
grep: /etc/mtab: No such file or directory
mount: /boot/efi: /dev/sda1 already mounted on /boot/efi.
Generating a RSA private key
...........................+++++
...+++++
writing new private key to '//etc/refind.d/keys/refind_local.key'
-----
grep: /etc/mtab: No such file or directory
Processing triggers for libc-bin (2.31-13+deb11u5) ...
root@debian:/# refind-install
ShimSource is none
Installing rEFInd on Linux....
grep: /etc/mtab: No such file or directory
The ESP doesn't seem to be mounted! Trying to find it....
Mounting ESP (/dev/sda1) at /boot/efi
mount: /boot/efi: /dev/sda1 already mounted on /boot/efi.
ESP was found at /boot/efi using vfat
Found rEFInd installation in /boot/efi/EFI/refind; upgrading it.
Copied rEFInd binary files

Notice: Backed up existing icons directory as icons-backup.
Existing refind.conf file found; copying sample file as refind.conf-sample
to avoid overwriting your customizations.

grep: /etc/mtab: No such file or directory
Could not identify ESP in AddBootEntry()!
Existing //boot/refind_linux.conf found; not overwriting.
root@debian:/# 
```

**Comment by zdykstra** [comment]
Thank you for catching this bug in our documentation. I've pushed a fix that should address it.
