### ISSUE TITLE
It takes too long from the ZBM kernel start to the frontend (vmd + udev-settle hilarious couple?)

### ISSUE THREAD

**Issue by solbjorn** [zbm-dev/zfsbootmenu#416]
On the PC with Intel Storage (vmd) enabled, it takes around 30-40 seconds for the ZBM frontend to boot. `loglevel=7` shows that it the pause happens between "after udev settles, hey, I'm eudev" and "SCSI is initialized, vmd is initialized", so I suspect one or both to blame on.
With the standard Arch Linux initramfs, the regular kernel doesn't have any pause at that place, I only notice this when booting ZBM. I don't build ZBM binaries myself, just use the prebuilt ones (usually the latest from the CI).

The first photo is taken at the moment when it has a hard time, the second is `dmesg` output from the ZBM shell.

![PXL_20230313_211732203](https://user-images.githubusercontent.com/12006295/224836398-12203f38-67df-4c5b-86ce-244ae65a0018.jpg)
![PXL_20230313_212001109](https://user-images.githubusercontent.com/12006295/224836465-657fca15-8adf-42d7-857e-97b0a3a55c1e.jpg)

**Comment by zdykstra** [comment]
What version of ZFSBootMenu are you using? I assume 'vmd' is backed by a kernel driver of some kind; your best option is to just blacklist that driver on the ZFSBootMenu commandline.

**Comment by solbjorn** [comment]
Currently 989449cf46a2, but I've been observing it for quite some time already, so safe to say 2.0.0 and 2.1.0 are affected as well.
vmd is the name of the kernel driver which handles Intel Storage stuff. Without this module Linux won't even detect the SSDs/HDDs, so not an option :D (yeah, when Intel SST is on, kernel can't access storage directly)
Arch Linux etc. initramfs also contain it, as without it I wouldn't be able to even boot and mount the rootfs, but they don't have such delay ._.

**Comment by ahesford** [comment]
It doesn't look like your dmesg output has captured the point of the stall. All of the timestamps in your screenshot are in the range of 0.5--0.65 seconds since boot. If you're seeing a stall, it's later than this.

**Comment by solbjorn** [comment]
Ah, right, sorry. I got confused by that the stall actually occurs right at the moment when the log ends on the first photo. But seems like the kernel just doesn't print any messages during the stall, including a bunch of those which already were generated, but not printed.
The actual moment of the stall from the log is below. Looks like the ZBM kernel can't initialize ata7 and ata8 properly. IIUC those are two SATA-III hard disks, 3 and 10 Tb. Moreover, I remember I was trying to access them from inside the ZBM shell and they are not present in the system at all (e.g. `/dev/disk/` contains only SSD partitions).
I don't remember any other Linux envs where I'd see this -- all of them boot up really quickly and detect the HDDs just fine.

![PXL_20230319_211328515](https://user-images.githubusercontent.com/12006295/226210409-c596e189-0937-4b65-bfa6-9d65516e25ce.jpg)

**Comment by ahesford** [comment]
I think you avoid this altogether by building your ZBM image from a distribution that works with your hardware.

The release image is built from Void Linux and the problem is almost certainly a kernel driver issue. You can try booting a Void live image to see if the problem occurs there as well. Either way, likely candidates different kernel configs, lists of loaded kmods or udev rules.
