### ISSUE TITLE
Update Documentation to mention Debian 12 Bookworm (successful installation)

### ISSUE THREAD

**Issue by lnxsrt** [zbm-dev/zfsbootmenu#425]
I recently followed the Debian Bullseye UEFI setup instructions, but installed Debian 12 Bookworm instead of Bullseye. It worked flawlessly with no alterations (besides `s/bullseye/bookworm/g`) needed to the docs. I used a Single Disk, so I can't speak for the other installation options, but those should work fine as well.

**Comment by zdykstra** [comment]
Great, thanks for the confirmation. I should be able to push a docs update to include a guide for that release.

**Comment by Anonymo** [comment]
Is there a link to see the WIP guide, since Debian was just released?

**Comment by classabbyamp** [comment]
See the CI results for https://github.com/zbm-dev/zfsbootmenu/pull/426
