### ISSUE TITLE
[DOCUMENTATION] Unable to install ZBM and Alpine on new disk following the official guide

### ISSUE THREAD

**Issue by clarenceab** [zbm-dev/zfsbootmenu#435]
Hello, following the advice given on IRC I'm opening this issue about installing Alpine along with ZBM using the official guide. 

I've tried from version 3.16.2 to the latest, 3.18.2 with no success. 
This is a one encypted disk only setup, on metal (x86_64 if it matters). 

Going step by step with the guide, the part when it always fail is, after installing the distro and chrooting into the new system, the enabling startup services. Everytime I want to setup udev as the device manager, it complains about not having the mdev service added to the sysinit runlevel. But when I do it, it disable the hwdrivers one, previosly added.

In one of my attempts, I was able to only active mdev service, and complete the steps of the guide, but when i tried to export the zpool, I couldnt do it because it was busy the command complained.

https://gitlab.alpinelinux.org/alpine/aports/-/issues/14046
It may be relevant? Ive read the ZBM guide was created before that commit made it to the Alpine 3.16.2 release IIRC.

Thanks in advance.

**Comment by clarenceab** [comment]
Presumably this is THE thing that (may) solve this
[https://gitlab.alpinelinux.org/alpine/alpine-conf/-/merge_requests/158](url)
 About quieting the `rc-update: service mdev is not in the runlevel sysinit` alert

**Comment by ahesford** [comment]
If you follow our guide and ignore the mdev message, does the installation work? Your linked "solution" is just "ignore the message [that we don't tell you to act on anyway]".

**Comment by clarenceab** [comment]
> If you follow our guide and ignore the mdev message, does the installation work? Your linked "solution" is just "ignore the message [that we don't tell you to act on anyway]".

No, because then setting up (e)udev as the dev manager doesn’t work. Thought that maybe that PR permits the script to actually work, but I’m no sure. 

I’d also see the existence of the `zfs-udev` package on Alpine that the guide doesn’t tell to install.

But again, just thinking about possible reasons.

**Comment by ahesford** [comment]
I just stipped the `udev` stuff from the Alpine guide. Making non-default device management work isn't really within the scope of our ZFS guides.

**Comment by clarenceab** [comment]
Um... Ok. Hope it works that way.

**Comment by ahesford** [comment]
It works fine in our Alpine testbed, where we don't fool around with `udev` at all. Users should customize the installation to their liking, fighting whatever upstream issues there may be.

**Comment by clarenceab** [comment]
Unfortunately, without that configuration the installation does still fail.
When I try to create the vfat filesystem with
`mkfs.vfat -F32 "$BOOT_DEVICE"`
I get
`mkfs.vfat: can't open '/dev/sda1': No such file or directory`

**Comment by ahesford** [comment]
Under the ["Define disk variables" section](https://docs.zfsbootmenu.org/en/v2.2.x/guides/alpine/uefi.html#define-disk-variables), note the comment:

> Verify your target disk devices with lsblk. /dev/sda, /dev/sdb and /dev/nvme0n1 used below are examples.

Most likely, your disk isn't `/dev/sda`.
