### ISSUE TITLE
set_rw_pool process hangs

### ISSUE THREAD

**Issue by klobik97** [zbm-dev/zfsbootmenu#446]
Hi, I would like to report a bug due to which I can't login to my system. My notebook power went down and after I charged it again, zfs started to give me the panic. I decided to go to recovery menu of zfsbootmenu and do a filesystem recover (scrub in zfs terminology), but program hangs when I try to make my pool not readonly - I can't stop it even with Ctrl-C. Screenshots attached. I will be glad to hear your suggestions on how to fix this little trouble! Thanks ;)
![20230713_193522](https://github.com/zbm-dev/zfsbootmenu/assets/139490592/f82e6a6b-31f7-47e1-b822-c293cb8917be)
![20230713_194301](https://github.com/zbm-dev/zfsbootmenu/assets/139490592/e940bcb4-47b1-41df-9b01-d9e8eaecb4f8)

**Comment by ahesford** [comment]
This is not really a ZFSBootMenu issue; the ZFS kernel driver is hung up trying to import the pool. You will have the same problem importing the pool in your regular operating system.

Sometimes imports can take a very long time, so I recommend waiting as long as you are willing before concluding that the pool is wedged and needs to be recreated from a backup.

**Comment by klobik97** [comment]
Okay, thank you. I wait for set_rw_pool command for more than 30 minutes as for now. Sadly, I don't have any backups. Do you think I'm screwed? Or is there any other way out of this situation?
