### ISSUE TITLE
Edit  kernel boot parameters on existing system

### ISSUE THREAD

**Issue by jakesteele** [zbm-dev/zfsbootmenu#463]
Hey,

Just hoping you can help me out,

I was hoping to edit the  kernel boot parameters and add `init_on_alloc=0` to my existing system that uses ZFSBootMenu. I used the direct method. 

(great work by the way)

**Comment by ahesford** [comment]
Use the [`zbm-kcl` utility](https://github.com/zbm-dev/zfsbootmenu/blob/master/bin/zbm-kcl), which you can just download and put anywhere in your `$PATH`. If you've set the `org.zfsbootmenu:commandline` property on your root filesystem, just run

    zbm-kcl -e

and it should load what is currently set and allow you to edit it. If you've set the property on some parent filesystem, you can just run

    zbm-kcl -e pool/filesystem

to select a specific filesystem where these edits should apply.

**Comment by jakesteele** [comment]
That worked perfectly :D thanks!
