### ISSUE TITLE
The EFI builds do include cryptsetup but not dm-crypto Kernel module

### ISSUE THREAD

**Issue by longsleep** [zbm-dev/zfsbootmenu#468]
I am trying zfsbootmenu and while converting my system which uses luks encrypted boot partition (and in there the boot pool), i noticed that the current release builds of zfsbootmenu have cryptsetup but no dm-crypto kernel module, making the device mapper fail to actually hook the opened luks device with error "crypt: unknown target type". This might be just an oversight, not sure thus here it is reported.

**Comment by ahesford** [comment]
The release image shouldn't even have `cryptsetup`, but the recovery image explicitly adds it; #470 should add the requisite module. Is there anything besides `dm-crypt` required to make `cryptsetup` work?

**Comment by ahesford** [comment]
If you find anything else required to make cryptsetup work, please comment here or open a new issue.

**Comment by longsleep** [comment]
Thanks! The "rescue" scenario was what I was dealing with and I think its great to have functional cryptsetup in the rescue image. I will create another ticket with one other struggle I encountered (https://github.com/zbm-dev/zfsbootmenu/issues/471).
