### ISSUE TITLE
Possible issue with Debian 11 instructions

### ISSUE THREAD

**Issue by stuart-mclaren** [zbm-dev/zfsbootmenu#489]
Hi,

I'm following the Debian instructions listed here:

https://docs.zfsbootmenu.org/en/latest/guides/debian/bullseye-uefi.html

The instructions say to:

Download the latest Debian Bullseye (11) Live image

After some commands you are instructed to run:

```
zpool create -f -o ashift=12 \
 -O compression=lz4 \
 -O acltype=posixacl \
 -O xattr=sa \
 -O relatime=on \
 -o autotrim=on \
 -o compatibility=openzfs-2.1-linux \
 -m none zroot "$POOL_DEVICE"
```

but this gives

```
property 'compatibility' is not a valid pool property
```

For Debian 11, it looks like the documented command should instead be:

```
zpool create -f -o ashift=12 \
 -O compression=lz4 \
 -O acltype=posixacl \
 -O xattr=sa \
 -O relatime=on \
 -o autotrim=on \
 -m none zroot "$POOL_DEVICE"
```

(or, maybe, a compatability mode that is understood by the Debian 11 live image).

**Comment by zdykstra** [comment]
What's the output of `zfs --version` for your system that doesn't have the `compatibility` pool property?

**Comment by stuart-mclaren** [comment]
```
zfs-2.0.3-9+deb11u1
```

**Comment by stuart-mclaren** [comment]
```
$ cat /etc/debian_version 
11.7

```

**Comment by zdykstra** [comment]
The Debian 11 guide was left in place since it was already written/working. However, I'd rather not start special-casing the documentation for an older version of Debian, so instead it's been removed.
