### ISSUE TITLE
zfs 2.2 image?

### ISSUE THREAD

**Issue by darkbasic** [zbm-dev/zfsbootmenu#495]
I (stupidly) upgraded to zfs 2.2 features thinking that zfsbootmenu 2.2 would support it, but apparently it uses zfs 2.1 so I'm locked out of my system.
I've tried to build my own image using zfsbootmenu from the AUR but apparently it doesn't boot: https://aur.archlinux.org/packages/zfsbootmenu#comment-936317
I've also tried to build a new image using the Dockerfile (which results in a bootable image) but apparently void doesn't have a zfs 2.2 package, [except from a PR on github](https://github.com/void-linux/void-packages/pull/45365#issuecomment-1741852176).
By any chance do you know how to build an image with zfs-2.2 or do you have an rc image available that I can use?
Thanks

**Comment by classabbyamp** [comment]
see https://github.com/zbm-dev/zfsbootmenu/discussions/485#discussioncomment-7000323

**Comment by darkbasic** [comment]
Thanks!!!!

**Comment by darkbasic** [comment]
If someone else ends up needing it here is the image I've built: https://raw.githubusercontent.com/darkbasic/gentoo-files/master/zfsbootmenu-zfs-2.2.0-rc3.EFI
