### ISSUE TITLE
Unable to mask teardown scripts.

### ISSUE THREAD

**Issue by geekifan** [zbm-dev/zfsbootmenu#502]
I set `org.zfsbootmenu:commandline="quiet loglevel=4 zbm.hookroot=UUID=XXXX-XXXX//EFI/zfsbootmenu/hooks"` and I am sure the UUID (a vfat EFI partition) is correct here. I also put an empty script named `90-xhci-unbind.sh` inside `hooks/teardown.d`. But zbm continues to teardown an USB keyboard before entering kernel.

**Comment by ahesford** [comment]
This will get easier when https://github.com/zbm-dev/zfsbootmenu/commit/ff5956298ab103b654606f6cfefc7c5343124926 makes it into v2.3.

Is this one of our binary releases? The v2.2 series still installs the hook as `xhci-tear down.sh`, with no numeric prefix. You can confirm the name by dropping to an emergency shell with `Ctrl+R` in the menu and looking at the contents of `/libexec/teardown.d`.

**Comment by geekifan** [comment]
Yes, I am using the binary release. I've tried to rename the dummy teardown script to the same name as the one in /libexec.teardown.d. But it doesn't work. My machine is a supermicro server and it has a virtual keyboard, which is disabled by zbm before kernel boot. I cannot control my server in IPMI using the virtual keyboard so I have to find a proper way to disable the teardown script.

**Comment by ahesford** [comment]
I suspect you are unable to mount the EFI system partition from the ZFSBootMenu image because it lacks the necessary modules for FAT filesystem support. Can you drop to a recovery shell and try `mount UUID=XXXX-XXXX /tmp` or something similar?

**Comment by geekifan** [comment]
After I installed zbm, I found out the vfat EFI partition `/dev/sda1`  containing the zbm boot EFI file according to the result of `blkid` and successfully mounted it using `mount /dev/sda1 /boot/efi` in the recovery shell. I created the dummy hook script inside the recovery shell, so I don't think that it lacks the necessary modules for FAT fs support.But I haven't tried to mount it using uuid because I cannot reboot my server recently. 

The directory structure of my EFI partition is:

```
|- EFI
    |- ZBM
        |- VMLINUZ.EFI
        |- VMLINUZ_BACKUP.EFI
        |- hooks
            |- early-setup.d
            |- setup.d
            |- teardown.d
                |- xhci-teardown.sh (an empty shell script that does nothing)
```

As a workaround, I can drop to the recovery shell and delete the hookscipt`/libexec/teardown.d/xhci-teardown.sh` in the memory filesystem of zbm temporarily so my server can boot into the system without virtual keyboard failure (but next time I still have to perform the same thing to make my virtual keyboard work).

**Comment by geekifan** [comment]
I decide to wait for the release of v2.3. The commit you mentioned is awesome! Thanks a lot!!

**Comment by geekifan** [comment]
Thanks you so much! I am not so familiar with UEFI boot so I confused kernel parameter with `org.zfsbootmenu:commandline`. Your solution works like a charm! I added the kernel boot parameter into the zbm boot entry using eifbootmgr and successfully skipped the teardown hook.
