### ISSUE TITLE
Incompatible with recommended upstream and Ubuntu dataset layout

### ISSUE THREAD

**Issue by almereyda** [zbm-dev/zfsbootmenu#510]
In https://github.com/openzfs/zfs/issues/15261 it was suggested to switch to ZFSBootMenu for recovering a failed GRUB boot.

> Suggestion: Switch to ZFSBootMenu and forget about GRUB (and its inability to fully deal with ZFS features).

Unfortunately ZFSBootMenu does not support to separate `bpool` and `rpool`. As per https://docs.zfsbootmenu.org/en/latest/man/zfsbootmenu.7.html the kernel root dataset is inferred from the boot environment and assumed to be on the same dataset, with no manual override foreseen:

> Never set the root= argument; ZFSBootMenu always sets this option based on the selected boot environment.

It is possible to install ZFSBootMenu on Ubuntu, which uses [the recommended file system layout for ZFS](https://openzfs.github.io/openzfs-docs/Getting%20Started/Ubuntu/Ubuntu%2020.04%20Root%20on%20ZFS.html), with following only the last steps from the Ubuntu UEFI instructions and manually mounting (+ unmounting) the ESP:

- https://docs.zfsbootmenu.org/en/v2.2.x/guides/ubuntu/uefi.html#install-zfsbootmenu
- https://docs.zfsbootmenu.org/en/v2.2.x/guides/ubuntu/uefi.html#configure-efi-boot-entries

Yet it will crash into the ZFSBootMenu recovery console.

Patching the `zkexec` command is needed to allow to boot the Kernel, since there is an assumption that the boot environment is to be found in a `boot` subdirectory of the dataset in question, and not at it's root, as is the case with Ubuntu.

Still this will not allow to sufficiently set the `root=` parameter, directly crashing into the Kernel's BusyBox ash:

```
cp /usr/sbin/zkexec /usr/sbin/zkexec2
sed 's|/boot||g' -i /usr/sbin/zkexec2
zkexec2 bpool/BOOT/ubuntu_abcdef vmlinuz-6.5.0-9-generic initrd.img-6.5.0-9-generic
```

**Comment by ahesford** [comment]
https://docs.zfsbootmenu.org/en/v2.2.x/guides/general/bootenvs-and-you.html

We will never support a separate boot pool. It's a terrible idea that leads to misery. Copy the files from your boot filesystem to `/boot` on your root.

**Comment by ahesford** [comment]
You should know that the guides hosted by OpenZFS are written by third parties, not by the ZFS team. I don't know whether the ZFS team has a position on any pool or file system layout, but in any case it wouldn't be relevant here.

Read our primer for a discussion on the merits of atomicity and, if you need some corroborating evidence, browse r/zfs on Reddit for the smorgasbord of "screwed by GRUB" posts. ZFSBootMenu exists precisely because the desire for GRUB compatibility leads to nothing but heartache.

**Comment by almereyda** [comment]
Thank you for the hints!
