### ISSUE TITLE
dracut: FATAL: No or empty root=

### ISSUE THREAD

**Issue by Sithuk** [zbm-dev/zfsbootmenu#516]
I got the following error following the rEFInd screen when I tried a recent ubuntu install.
dracut: FATAL: No or empty root=

I resolved by adding the following to the kernel parameters in refind_linux.conf, where zpool is the name of the pool. Zfsbootmenu then started normally.
root=zfs:zpool/ROOT

https://github.com/openzfs/zfs/blob/master/contrib/dracut/README.md

Does the rEFInd section of the ubuntu install guide need to be updated?

**Comment by zdykstra** [comment]
How did you install ZFSBootMenu - from source (via a tagged release, or master) or a prebuilt EFI?

**Comment by zdykstra** [comment]
I highly recommend that you use the git branch from which releases are tagged - in this case v2.2.x. master is a moving target that might or might not be fit for consumption.

**Comment by Sithuk** [comment]
Thank you Zdykstra. I installed from master as part of testing the Ubuntu zfsbootmenu install script.

What changed to cause the break? Something in upstream dracut?

Thank you for the info on the master vs branches. The Ubuntu zfsbootmenu install script currently installs from master. I’ll have to think through what I should link to in future if the master “might or might not be fit for consumption”. I don’t think I can link to a branch as that might eventually be deleted? Is there a link that will always download the latest branch code that I could use?

**Comment by ahesford** [comment]
The v2.2.x branch will never be deleted.

If you want the latest, you can use https://get.zfsbootmenu.org/, which is just a thin wrapper over the GitHub release query interface.

**Comment by ahesford** [comment]
As a side note, if you're going it query GitHub directly, you should use `jq` or some other mechanism that understands the structure of the JSON response. Unstructured text processing is bound to fail at some point.
