### ISSUE TITLE
curl gives SSL error when downloading ZBM prebuilt EFI file

### ISSUE THREAD

**Issue by karlgrose** [zbm-dev/zfsbootmenu#519]
This is the command used:
```
curl -o /boot/efi/EFI/ZBM/VMLINUZ.EFI -L https://get.zfsbootmenu.org/efi
```
This is the error:
```
curl: (60) SSL: no alternative certificate subject name matches target host name 'get.zfsbootmenu.org'
```

**Comment by ahesford** [comment]
Thanks for reporting this. Seems like our certs were scrambled when we added a new `zfsboot.menu` domain for fun. Until we sort this out, you can just grab `https://get.zfsboot.menu/efi` if you don't want to see the certificate error.

You can also have confidence that the images are as we released them by [checking the signature of the EFI executable](https://docs.zfsbootmenu.org/en/v2.2.x/#signature-verification-and-prebuilt-efi-executables), even if you don't trust the download source.

**Comment by zdykstra** [comment]
Thanks for the report. I've corrected the problem and both https://get.zfsbootmenu.org and https://get.zfsboot.menu now work as expected.
