### ISSUE TITLE
installing zfsbootmenu 2.3.0 on arch results in error

### ISSUE THREAD

**Issue by wboschman** [zbm-dev/zfsbootmenu#588]
### ZFSBootMenu build source

Release EFI

### ZFSBootMenu version

2.3.0

### Boot environment distribution

arch linux

### Problem description

Hi,]

I get his error while building

```
Updating zfsbootmenu/zbm-release
Updating bin/generate-zbm
sed: -e expression #1, char 45: unterminated `s' command
make: *** [Makefile:36: zbm-release] Error 1
==> ERROR: A failure occurred in package().
```

problem might come from line 35 releng/version.sh:

```
  # Otherwise, use git-rev-parse if possible
  if branch="$(git rev-parse --abbrev-rev HEAD 2>/dev/null)"; then
```

should be:

```
  # Otherwise, use git-rev-parse if possible
  if branch="$(git rev-parse --abbrev-ref HEAD 2>/dev/null)"; then
```

### Steps to reproduce

yay -S zfsbootmenu

**Comment by ahesford** [comment]
I cannot reproduce this:
```sh
mkdir -p test/root
cd test
curl -L https://github.com/zbm-dev/zfsbootmenu/archive/v2.3.0.tar.gz | tar xzvf -
cd zfsbootmenu-2.3.0
make DESTDIR="../root"
```
successfully installs ZFSBootMenu with a valid `usr/share/zfsbootmenu/zbm-release` as written by `releng/version.sh`.

The Makefile is also used in the same way to build the Void Linux package. Is `pkgbuild` or yay doing something weird?

**Comment by wboschman** [comment]
I've followed your steps and this works fine for me.

I don't have much insight in in the workings of makepkg but I think the problem is caused by the separate build and source dirs.

**Comment by wboschman** [comment]
additionally when doing it manually the file zfsbootmenu/zbm-release looks like this:

NAME="ZFSBootMenu"
PRETTY_NAME="ZFSBootMenu"
ID="zfsbootmenu"
ID_LIKE="void"
HOME_URL="https://zfsbootmenu.org"
DOCUMENTATION_URL="https://docs.zfsbootmenu.org"
BUG_REPORT_URL="https://github.com/zbm-dev/zfsbootmenu/issues"
SUPPORT_URL="https://github.com/zbm-dev/zfsbootmenu/discussions"
VERSION="2.3.0"

with makepkg it get:

NAME="ZFSBootMenu"
PRETTY_NAME="ZFSBootMenu"
ID="zfsbootmenu"
ID_LIKE="void"
HOME_URL="https://zfsbootmenu.org"
DOCUMENTATION_URL="https://docs.zfsbootmenu.org"
BUG_REPORT_URL="https://github.com/zbm-dev/zfsbootmenu/issues"
SUPPORT_URL="https://github.com/zbm-dev/zfsbootmenu/discussions"
VERSION="--abbrev-rev
53e601974ca8ee56461131c32bab70bafcb3684e (53e6019)"

**Comment by scotte** [comment]
It does look like it's related to the version parsing - I can reproduce the same error locally:

```
$ git clone https://aur.archlinux.org/zfsbootmenu.git
$ cd zfsbootmenu
$ makepkg                                                                                                 master 
==> Making package: zfsbootmenu 2.3.0-1 (Sun 04 Feb 2024 09:42:20 AM MST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading zfsbootmenu-v2.3.0.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1846k    0 1846k    0     0  1647k      0 --:--:--  0:00:01 --:--:-- 11.3M
==> Validating source files with sha512sums...
    zfsbootmenu-v2.3.0.tar.gz ... Passed
==> Extracting sources...
  -> Extracting zfsbootmenu-v2.3.0.tar.gz with bsdtar
==> Entering fakeroot environment...
==> Starting package()...
./releng/version.sh -u
Updating zfsbootmenu/zbm-release
Updating bin/generate-zbm
sed: -e expression #1, char 45: unterminated `s' command
make: *** [Makefile:36: zbm-release] Error 1
==> ERROR: A failure occurred in package().
    Aborting...
```

By making `releng/version.sh` `set-x`:

```
+ sed -e 's/our $VERSION.*/our $VERSION = '\''--abbrev-rev
53e601974ca8ee56461131c32bab70bafcb3684e (53e6019)'\'';/' -i bin/generate-zbm
sed: -e expression #1, char 45: unterminated `s' command
```

**Comment by ahesford** [comment]
Alright, I understand the problem. The fact that AUR stuff lives in a git repository, and that `makepkg` doesn't attempt to isolate the build environment, means that your host git is leaking into the build environment and then the git rev parsing is picking up the AUR package git root. Our version detection assumes that one of the following is true:
1. The ZBM tree is a git repository;
2. The ZBM tree is not a git repository and is not unpacked in some other git repository; or
3. The `git` executable is not available.

Arch packaging is kind of broken here. The right thing to do is not build the ZBM package as a child of a git repository, and also to prevent the host git from leaking into the environment. I'm not sure how to do this with `makepkg`.

If this needs to be worked around, patching the Makefile to make the `zbm-release` target a no-op.

**Comment by scotte** [comment]
Ha, indeed! A simple workaround:

```
$ rm -rf .git
$ makepkg
[...]
==> Finished making: zfsbootmenu 2.3.0-1 (Sun 04 Feb 2024 10:26:49 AM MST)
$ ls
pkg  PKGBUILD  src  zfsbootmenu-2.3.0-1-x86_64.pkg.tar.zst  zfsbootmenu-v2.3.0.tar.gz
```

Obviously that precludes the use of `yay`, etc, but it is a workaround and still using the AUR...

**Comment by wboschman** [comment]
it not so much git i think but the fact that "--abbrev-rev"  does not exist as a parameter it should be "--abbrev-ref".

**Comment by ahesford** [comment]
Ah, I couldn't see the difference in your "line should be" note. Thanks, this is definitely a big on our part. Curious that git isn't returning nonzero there.

**Comment by ahesford** [comment]
After fixing the typo and limiting the search for a git repository, I think this will build as expected even with the AUR helper. See #589.

**Comment by Darukutsu** [comment]
Still not fixed, [AUR](https://aur.archlinux.org/packages/zfsbootmenu) suggest to use workaround. Will this be fixed?

**Comment by ahesford** [comment]
There's nothing to fix on our end. We don't support the AUR, and whoever posted that PKGBUILD should avoid running our versioning script if Arch's build process can't stop leaking information into the build directory.

**Comment by erus** [comment]
> Still not fixed, [AUR](https://aur.archlinux.org/packages/zfsbootmenu) suggest to use workaround. Will this be fixed?

It _is_ fixed with https://github.com/zbm-dev/zfsbootmenu/commit/dae859df631bf994fb412e2b6d46b1179e02e2a5 but this commit has not yet been included in a release.
