### ISSUE TITLE
Shortcuts missing from /usr/bin

### ISSUE THREAD

**Issue by Sithuk** [zbm-dev/zfsbootmenu#616]
### ZFSBootMenu build source

Local build, dracut

### ZFSBootMenu version

master

### Problem description

The symlinks such as "zbm" and "poweroff" are missing from the zfs shell /usr/bin in a fresh install using the master. I am testing remote access to unlock a zfs on luks drive.

### Steps to reproduce

1. Compile from master.
2. Reboot.
3. Type zbm to start zfsbootmenu.

**Comment by zdykstra** [comment]
Are you SSH'ing in to ZFSBootMenu? If so, what SSH server do you have embedded in your image? What's the value of the `PATH` environment variable? What distribution are you building this on?

**Comment by Sithuk** [comment]
I am SSH'ing in, yes. 
Dropbear is embedded (SSH-2.0-dropbear_2020.81).
The PATH environment variable is: /zbm/bin:/usr/sbin:/usr/bin:/sbin:/bin
I built on Ubuntu 22.04.
"zbm" is not present in /usr/sbin of the zfsbootmenu initramfs shell. I didn't find it when I did a search using find either.

**Comment by zdykstra** [comment]
Is this issue still present in a build from the master branch? This was not able to be replicated locally.

**Comment by Sithuk** [comment]
Just carried out a test with the master branch. The zbm shortcut is still missing unfortunately. "zfsbootmenu" works fine.

**Comment by Sithuk** [comment]
I've updated the ubuntu zfsbootmenu install script. You can download the latest from the link below. That should help you duplicate the lack of zbm shortcut that I have experienced.
https://github.com/Sithuk/ubuntu-server-zfsbootmenu

**Comment by classabbyamp** [comment]
could you upload the generated zfsbootmenu files?

**Comment by ahesford** [comment]
This is a problem with the installation script called from the Makefile. I'll propose a fix later today.

**Comment by ahesford** [comment]
If the fix in #628 doesn't solve this problem, please let me know.
