### ISSUE TITLE
Add a debug flag to show what commands are being run

### ISSUE THREAD

**Issue by ericonr** [zbm-dev/zfsbootmenu#62]
This is not essential and I can try to implement when I get the time, would just be nice to have that, both for development as well as UX.

**Comment by zdykstra** [comment]
@ericonr just to confirm, you'd like this to be added to `generate-zbm` - specifically when `dracut` is called? Or did you have a broader scope in mind?

**Comment by ericonr** [comment]
Initially for dracut, so show something like 

```
$ generate-zbm --debug
Running command: dracut --confdir ...
```

Then for the rest, the diagnostic messages are already pretty good, but they could go further, with something like

```
Deleting bundles <name> <other-name> ...
```
