### ISSUE TITLE
ZFSBootMenu does not boot except when built with 6.5.13 (Void Linux).

### ISSUE THREAD

**Issue by Animeshz** [zbm-dev/zfsbootmenu#627]
### ZFSBootMenu build source

Local build, dracut

### ZFSBootMenu version

2.3.0

### Boot environment distribution

Void Linux

### Problem description

I found out that for the kernels `6.1.83 (lts)`, `6.6.30 (lts)`, `6.8.9 (latest, on void)` zfsbootmenu doesn't boot (stuck with a plain cursor).

The only version in my experimentation that worked was `6.5.13`. When built like `sudo generate-zbm --kver 6.5.13_1`.

I'm on Framework Laptop 13, i5-1135g7. The dmesg logs at the chroot of zfsbootmenu and at the distro didn't seem very useful, no major errors or red-lines (in the working 6.5.13 kernel), although if its required I may try to extract it from there.

Thanks!

### Steps to reproduce

My installation history is linked [here in my notes (see: click to view)](https://animeshz.github.io/site/notes/20-29--DevEnvironment/21--Linux/21.01-ZFS.html), with all the zfs pool, dataset options and zfsbootmenu config.

The reboot after that doesn't load the zfsbootmenu, I had to generate the zbm manually using the above command in problem description in order to actually make it boot.

**Comment by zdykstra** [comment]
This is for sure a kernel issue that is (effectively) out of our hands. Unfortunately there's little to nothing we can do.

**Comment by Animeshz** [comment]
:thinking: interesting, looks like to me too, a reddit post shows [a update pushed into 6.6 on fedora made is possible to boot, which was not booting previously](https://www.reddit.com/r/zfs/comments/18aipsj/zfsbootmenu_failing_to_boot_fedora_correctly/).

I just posted here so that I could have a record, I'm going to see the differences in void kernel build options next...

**Comment by zenodotus280** [comment]
It sounds like you're having the same problem I am: #626 
For what it's worth, I am able to boot into a VM with the exact same install script that fails on my desktop. At what stage are you introducing `enerate-zbm --kver 6.5.13_1`? I am effectively following the official ZBM instructions to the letter. I'm also installing to NVMe which is the only notable difference to my VMs.

Also: that's a cool personal website!

**Comment by Animeshz** [comment]
> At what stage are you introducing `enerate-zbm --kver 6.5.13_1`? I am effectively following the official ZBM instructions to the letter. I'm also installing to NVMe which is the only notable difference to my VMs.

Its the very last step, actually the 4th line from the last (in my installation logs). 😇

**Comment by zenodotus280** [comment]
I just added a line to my own script to install the 6.5 headers and then kernel before exiting the chroot and I was able to successfully boot in. Thanks!

**Comment by classabbyamp** [comment]
fixed by a revert in the upstrema kernel
