### ISSUE TITLE
ZFSBootMenu not booting from EFI shell on Udoo X86

### ISSUE THREAD

**Issue by plbertrand** [zbm-dev/zfsbootmenu#634]
### ZFSBootMenu build source

Release EFI

### ZFSBootMenu version

2.3.0

### Boot environment distribution

Unsure I get to a boot environment

### Problem description

Trying to run the EFI executables I get "Unable to locate embedded . linux section: Invalid Parameter"

### Steps to reproduce

1. I copied ZFSBootMenu next to Grub on the EFI partition
1. Restarted and manually went into the internal EFI shell of the Udoo X86. Unfortunately, Udoo is not releasing newer InsydeH2O BIOS (2020-08-17 from [here](https://www.udoo.org/docs-x86/Advanced_Topics/UEFI_update.html)).
1. cd EFI\BOOT
1. VM_LINUZ.EFI
1. Even tried very old version (i.e. 1.9 and 1.10) in case it was a regression over time

All of them report: "Unable to locate embedded . linux section: Invalid Parameter"

![IMG_0179](https://github.com/zbm-dev/zfsbootmenu/assets/11807652/9afecfaa-1e36-4f81-a666-9dd17ed9b627)

**Comment by classabbyamp** [comment]
you may need to use rEFInd. have you tried that?

**Comment by plbertrand** [comment]
No I haven't. What would rEFInd do different here? Is it to load it first such that "limited" systems can boot and then I chainload ZFSBootMenu?

**Comment by classabbyamp** [comment]
in some cases, UEFI implementations can do weird things, and rEFInd is good at smoothing over those wrinkles. It would load either the ZBM EFI or the ZBM components build

**Comment by plbertrand** [comment]
Thanks! I'll give it a spin and report back.

**Comment by plbertrand** [comment]
Yeah no luck with rEFInd. I added refind_linux.conf next to VM_LINUZ.EFI, zfsbootmenu-x86_64-v1.9.0.EFI and zfsbootmenu-x86_64-v1.10.0.EFI. 

```
"Boot default"  "zbm.prefer=rpool ro loglevel=4 zbm.skip nosplash"
"Boot to menu"  "zbm.prefer=rpool ro loglevel=4 zbm.show nosplash"
```

rEFInd did find all three efi loader by itself even giving the penguin logo for VM_LINUZ.EFI. 

Loading VM_LINUZ.EFI yielded:
![IMG_0180](https://github.com/zbm-dev/zfsbootmenu/assets/11807652/9ca3e8c4-2d0b-48ee-993b-a5f86c50d36d)

Loading zfsbootmenu-x86_64-v1.9.0.EFI or zfsbootmenu-x86_64-v1.10.0.EFI yielded:
![IMG_0181](https://github.com/zbm-dev/zfsbootmenu/assets/11807652/6abd42cc-c187-4a7f-aace-8d187604ce0e)

I'm running out of ideas, especially since the computer is not really verbose here.

**Comment by ahesford** [comment]
When using rEFInd, you should prefer the ZBM components rather than an EFI bundle.

**Comment by plbertrand** [comment]
That did it! Thank you.
