### ISSUE TITLE
Problems on Ubuntu 24.04

### ISSUE THREAD

**Issue by mrichtarsky** [zbm-dev/zfsbootmenu#639]
### ZFSBootMenu build source

Local build, dracut

### ZFSBootMenu version

2.3.0

### Boot environment distribution

Ubuntu 24.04 server

### Problem description

Thanks for this interesting project!

So I followed this guide:
https://docs.zfsbootmenu.org/en/v2.3.x/guides/ubuntu/uefi.html

I tried to install on Ubuntu 24.04, not sure if that is supported yet. I also used the server image and ran everything from a shell, did not use the live image.

- In section "Install ZFSBootMenu", I used the "Source" option. This does not install curl and thus the curl command fails. Can be solved by installing curl, I can open a PR to change this in the docs
- At the last step "generate-zbm" I got an error that no UEFI stub could be found. Some research showed that this is part of systemd-boot, so I installed it. However the installation also wrote some stuff to /boot. Sorry, I don't have the exact output but it's possible that something happened which could explain the problem below

After rebooting, the system could not boot up. It was stuck at a initramfs and complained that no "root=" was specified.

At that point I gave up and did a normal Ubuntu install on a small ext4 partition :(

### Steps to reproduce

Please see above, sorry that I don't have exact error messages.

**Comment by zdykstra** [comment]
The documentation is for Ubuntu 22.04, so some parts of it will not apply directly to Ubuntu 24.04. A full reworking of the guide will need to happen to bring it up to spec for 24.04.
