### ISSUE TITLE
Incomplete Ubuntu 22.04 UEFI instructions lead to broken network support

### ISSUE THREAD

**Issue by ssokolow** [zbm-dev/zfsbootmenu#649]
### ZFSBootMenu build source

Release EFI

### ZFSBootMenu version

2.3.0

### Boot environment distribution

Ubuntu 22.04

### Problem description

Following the instructions for setting up an Ubuntu 22.04 boot environment doesn't account for important differences between what debootstrap installs and what the search-engine-visible distro docs assume will have been installed by the regular installer.

Most notably:

* It just assumes that debootstrap or the `ubuntu-desktop` metapackage will set up DHCP... which is untrue.
* If you add in [Managing Redundant ESPs with mdraid](https://docs.zfsbootmenu.org/en/v2.3.x/general/mdraid-esp.html), "Depending on the distribution, additional setup may be required to assemble the mdraid array on boot. Consult your distribution's documentation for more information." is inadequate because debootstrap doesn't install the `mdadm` package but the Ubuntu docs assume it'll have been installed by default by the regular install ISO.  For that one, I had to just guess my way to fixing that.

In both cases, the problem comes down to "ZFSBootMenu guides the user through an install process that omits steps/packages the distro docs assume will have been performed/installed by the more traditional install procedure".

As a result, I followed some third-party instructions for adding networking to a debootstrap install that involved systemd-networkd, but it left me with a machine that can see the outside world, but anything else on the same LAN gives "No route to host" when trying to reach it (WTF? You're on the same subnet, DHCPed from the same server!) so I'm stuck preparing to manually `diff` my Kubuntu CD install'd laptop's `/etc` against my ZFSBootMenu instruction'd desktop's `/etc` to figure out how Canonical *expects* DHCPed networking to work in 22.04.

### Steps to reproduce

1. Follow the  instructions at https://docs.zfsbootmenu.org/en/v2.3.x/guides/ubuntu/jammy-uefi.html
2. Once rebooted into the new environment, try running `sudo apt-get update` or anything else that requires an active network connection.

**Comment by ahesford** [comment]
Our guides are intended as overviews to illustrate the disk layout and expected by ZFSBootMenu and to provide an environment capable of building ZFSBootMenu images on the local host. They are not intended to provide comprehensive coverage of the installation process of every distribution.

We assume that users following our guides will have the basic Linux and Unix system administration abilities necessary to configure their environments as they see fit. Hence, in the Ubuntu guides, we note that "[a]ny additional software should be selected and installed at this point." User judgment is expected.

We happily welcome pull requests to refine the language or improve clarity of our guides, although there is some line that demarcates "refinement" and "providing remedial introduction", which is out of scope.

In the meantime, we do not consider this a bug.

**Comment by ssokolow** [comment]
If it's not meant to go that far, then why does it mention "Any additional software should be selected and installed at this point. For a normal desktop experience, install the ubuntu-desktop meta package."?

I think "For a normal desktop experience, install the ubuntu-desktop meta package." is a bug, since doing so does not result in a normal desktop experience but gives readers the impression that it will.

**Comment by ssokolow** [comment]
Also, for anyone who finds this via search engine, here are the two differences I found:

1. debootstrap doesn't create the `/etc/netplan/01-network-manager-all.yaml ` file that the regular *buntu installer does. It's supposed to contain the following:

    ```yaml
    # Let NetworkManager manage all devices on this system
    network:
      version: 2
      renderer: NetworkManager
    ```

    That'll get you networking but...

2. Something about the debootstrap install flow pulled in `firewalld` when the regular 22.04 LTS installer didn't, which was stacking up with my usual UFW and causing all sorts of confusing problems. Just remove one of them and ask the other to flush and rebuild things. (eg. `sudo ufw reload`)

**Comment by ahesford** [comment]
dba12663f4ec3facfb6e72f04666f001bc02f7ad

**Comment by ssokolow** [comment]
That works. Thanks.

**Comment by valarauca** [comment]
Came around to praise this guide, but as a more experienced linux user it wasn't hard to setup networking 

---

Stumbling into the same problem

[This is the post setup I did](https://github.com/valarauca/remember/blob/master/zfs/boot_drive_ubuntu.md). The guide assumes you'll be capable of poking around in you `/sys/class/networking` directory to find your interface name (mine was `e7ps0`).

From there you can basically install `ubuntu-desktop` to get the normal GUI you expect. A lot of guides exist to coy invert an ubuntu headless server into a fully fledged desktop and those will carry you across the finish line.

The only important step I'd note is disabling grub, via `apt/priorities.d/*` as I believe that can break your ZFS boot agent(?)
