### ISSUE TITLE
Cannot get to boot "Execution of embedded linux image failed: Out of Resources"

### ISSUE THREAD

**Issue by BloodyIron** [zbm-dev/zfsbootmenu#655]
### ZFSBootMenu build source

Recovery EFI

### ZFSBootMenu version

2.3.0

### Boot environment distribution

Portable

### Problem description

I've tried the Portable and the Ubuntu install guide, and both result in "Execution of embedded linux image failed: Out of Resources". I'm trying to boot from a USB drive to then trigger the boot of a TrueNAS install on an NVMe PCIe adapter that my Dell R720 cannot directly boot from.

### Steps to reproduce

Follow the instructions for portable ( https://docs.zfsbootmenu.org/en/v2.3.x/general/portable.html ) or Ubuntu 24.04 ( https://docs.zfsbootmenu.org/en/v2.3.x/guides/ubuntu/noble-uefi.html ).

**Comment by BloodyIron** [comment]
![image](https://github.com/user-attachments/assets/a5882506-a468-48e1-b78b-f837b31c7933)

So this is the error I get regardless of if I go through the extensive hoops of installing Ubuntu as per the guide onto the USB Thumbdrive, or using the Portable edition.

I cannot for the life of me get ZFS Boot Menu to actually boot, and quite frankly the documentation is really lacking for determining "what I want" in terms of the section of the documentation.

Each section is written as if the reader already knows what they want, but a lot of us don't. I just want a USB Thumb drive to boot the PCIe NVMe device I have that already has boot capabilities installed, but the Dell R720 cannot directly boot to NVMe devices without physical boot roms on them. That's why I'm trying to get ZFS Boot Menu to work. And not only am I not able to get it working, I don't even know what method for setup I should use in this scenario! :/

**Comment by zdykstra** [comment]
This isn't a ZFSBootMenu bug, it's Dell R*20 generation UEFI implementations being trash. You should be able use rEFInd to boot ZFSBootMenu on your hardware.

**Comment by BloodyIron** [comment]
> This isn't a ZFSBootMenu bug, it's Dell R*20 generation UEFI implementations being trash. You should be able use rEFInd to boot ZFSBootMenu on your hardware.

I used rEFInd in the Ubuntu attempt I made by the way, which also resulted in the same error once I made the appropriate menu selection rEFInd offered. Also, there's other people reporting success with ZFS Boot Menu on R720's for TrueNAS, which is how I arrived at this tool in the first place.

So... what now then?

**Comment by zdykstra** [comment]
Use rEFInd to boot the component release - it's just a kernel and initramfs.

**Comment by BloodyIron** [comment]
> Use rEFInd to boot the component release - it's just a kernel and initramfs.

Did you not read what I just wrote? I said I did that. I followed the Ubuntu documentation which says to do that and still got this result.

**Comment by zdykstra** [comment]
Nowhere in your replies do you mention using the component release of ZFSBootMenu, and the initial bug report mentions the EFI build. rEFInd can and does boot the bare ZBM kernel and initramfs on that generation of hardware, since there's no EFI stub loader involved.

**Comment by ahesford** [comment]
The best way to rage against your own ignorance is to work to eliminate it, not lash out at people who offer guidance.

[As I've explained elsewhere](https://github.com/zbm-dev/zfsbootmenu/issues/649#issuecomment-2211897008), our guides are not written to help you figure out what you want, but to illustrate how to:
1. Provide ZFSBootMenu with the disk layout it demands to boot your system, and
2. When possible, ensure that your installation provides the components necessary to build a local image.
Take some time to learn some basics and think your way through problems rather than wailing every time you hit the limits of your understanding.
