### ISSUE TITLE
Failed to start Switch Root

### ISSUE THREAD

**Issue by artyom-dot** [zbm-dev/zfsbootmenu#81]
I installed Debian Buster with root on ZFS with `rEFInd` as UEFI boot manager, `dracut` as initramfs generator, `systemd` as init system. Everything was ok so i tried to install zfsbootmenu (i cloned repo, `make install`ed, installed perl libs, kexec-tools, fzf, mbuffer) pasted config, set zfs property, generated boot environment (`generate-zbm`), and rebooted. Boot failed with `Failed to start Switch Root` error. So my question is there something i've done wrong? Boot without zfsbootmenu works.
My ZFS topology
| NAME| MOUNTPOINT | CANMOUNT
|-------------------------------|------------|---------|
| zroot                         | none       |on |
| zroot/ROOT                    | none       | off |
| zroot/ROOT/debian.d2020.09.18 | /          | noauto |
| zroot/home                    | /home      | on |

zroot is encrypted, `keylocation=prompt`

|NAME|        PROPERTY|                     VALUE|                         SOURCE|
|--------|---------------------------------|--------------|------------|
|zroot/ROOT|  org.zfsbootmenu:commandline|  spl_hostid=2c9a715c ro quiet|  local|

I've tried to copy full rdsosreport.txt but there were no sda1 in /dev to mount. I don't know any other way to save it.

End of journal
![journalctl-end](https://user-images.githubusercontent.com/71446314/93617940-2488b000-f9c6-11ea-8c51-8c7cd524e11d.png)

dracut state
![dracut](https://user-images.githubusercontent.com/71446314/93618579-feafdb00-f9c6-11ea-9e94-43fe2ee2dadc.png)

<details>
  <summary>refind_linux.conf</summary>
"Boot default"  "zfsbootmenu:ROOT=zroot spl_hostid=2c9a715c timeout=0 ro" <br/>
"Boot to menu"  "zfsbootmenu:ROOT=zroot spl_hostid=2c9a715c timeout=-1 ro"
</details>

zfsbootmenu config
[config.txt](https://github.com/zbm-dev/zfsbootmenu/files/5246662/config.txt)

dracut conf
[zol.txt](https://github.com/zbm-dev/zfsbootmenu/files/5246672/zol.txt)

`zfs-import.target` `zfs-mount.service` `zfs-import-cache` `zfs.target` systemd units are enabled.

I can share Virtualbox VM if needed

**Comment by zdykstra** [comment]
Are you able to boot into the ZFSBootMenu kernel/initramfs and have it successfully find the `zroot/ROOT/debian.d2020.09.18` boot environment, along with a kernel? When you hit the Switch Root error, is that after you've attempted to boot into the Debian environment, or is that in the ZFSBootMenu initrd/initramfs ?

**Comment by artyom-dot** [comment]
I'm not able to boot ZFSBootMenu initramfs. I can't reach boot environment selection.
rEFInd -> select zfsbootmenu -> error

**Comment by artyom-dot** [comment]
kernel version 4.19.0, ZOL version 0.8.4

**Comment by zdykstra** [comment]
Can you share the ZFSBootMenu initramfs and kernel that were built? I'd like to boot them / inspect them locally.

**Comment by zdykstra** [comment]
Thanks! I see that your initramfs has the following modules:

```
bash
dash
systemd
systemd-initrd
console-setup
crypt
dm
dmraid
kernel-modules
lvm
mdraid
overlay-root
qemu
zfsbootmenu
lunmask
rootfs-block
terminfo
udev-rules
dracut-systemd
usrmount
base
fs-lib
shutdown
```
Can you try changing your omit modules to the following:

`omit_dracutmodules+=" btrfs systemd systemd-initrd dracut-systemd "` 

Then rebuild the initramfs and try from there? You can verify what modules were built in to the image by running `lsinitrd -m <path to your zfsbootmenu initramfs>`.

**Comment by zdykstra** [comment]
Just to clarify, this should be changed in `/etc/zfsbootmenu/dracut.conf.d/zfsbootmenu.conf` and NOT to `/etc/dracut.conf.d/zol.conf`.

**Comment by artyom-dot** [comment]
So, with `omit_dracutmodules+=" btrfs zfs resume systemd systemd-initrd dracut-systemd "` it works now but only with keylocation=prompt. If i set `keylocation=file:///etc/zfs/zroot.key`, `echo '12345678' > /etc/zfs/zroot.key` and add `install_items+=" /etc/zfs/zroot.key "` to `/etc/dracut.conf.d/zol.conf` it breaks but now it breaks after i choose boot environment from ZFSBootMenu with erorr `Failed to mount /sysroot` (with overlay-root and without)

**Comment by zdykstra** [comment]
With `keylocation=prompt`, you're able to fully boot a Debian Buster install and log in/otherwise use the system?

 Are you using Dracut to make the initramfs in the boot environment for kernel 4.19.0, or is that still being created by Debian's `update-initramfs` ? If that's still being created by update-initramfs, you'll have to make sure that `/etc/zfs/zroot.key` is copied into the initramfs through the official Debian mechanism. If the file isn't there, the decrypt_fs() function looks like it just retries a couple times and then errors out.

https://github.com/openzfs/zfs/blob/master/contrib/initramfs/scripts/zfs#L417

**Comment by artyom-dot** [comment]
oh i forgot to run dracut to regenerate initramfs with key, my bad, sorry, everything works with keylocation=file://..
thank you for your help

**Comment by artyom-dot** [comment]
so the whole problem is systemd was included in zfsbootmenu initramfs

**Comment by zdykstra** [comment]
Awesome! So just to confirm:

* Install `dracut` on Debian
* Install `zfsbootmenu`
* Set `omit_dracutmodules+=" btrfs zfs resume systemd systemd-initrd dracut-systemd "` in `/etc/zfsbootmenu/dracut.conf.d/zfsbootmenu.conf` 
* Set `install_items+=" /etc/zfs/zroot.key "` in /etc/dracut.conf.d/zol.conf

Then use `generate-zbm` to create a ZFSBootMenu initramfs, and `dracut` to create an initramfs in your boot environment? If that's correct, I'll add that to our project documentation.

**Comment by artyom-dot** [comment]
Install `zfs-dracut` (it includes zfs modules for dracut) `dracut` will be installed as dependency of `zfs-dracut` 
Also remove /etc/dracut.conf.d/10-debian.conf because of `hostonly="yes"` in it or set `hostonly="no"` in /etc/dracut.conf.d/zol.conf. I've encountered with errors because of it (dracut was trying to store current kernel cmdline ROOT=/dev/block)

I can create a wiki page with step by step guide (i've wrote a script) but there won't be many differences with the existing void linux installation

**Comment by artyom-dot** [comment]
also i don't know if it's needed but i've changed default init system (sysv-init) to systemd so maybe it should be mentioned in doc

**Comment by zdykstra** [comment]
If you could create a step-by-step guide, that would be a GREAT addition to the Wiki ! I don't have any practical experience using ZFS for the root filesystem on Debian, but I'd be happy to run through your guide as a tester. Thank you!

**Comment by artyom-dot** [comment]
ok, i hope my english is good enough

**Comment by zdykstra** [comment]
> ok, i hope my english is good enough

Ah, it'll be fine. I can go through it and modify the language a bit if there are any parts that aren't clear. Thank you again for your interest in ZFSBootMenu!
