### ISSUE TITLE
[Feature request] Make the snapshot screen more dummy proof

### ISSUE THREAD

**Issue by ericonr** [zbm-dev/zfsbootmenu#89]
- [x] Have help texts explaining each option (WIP)
- [x] Add job control to the duplicate process, otherwise a user can get stuck waiting for it to complete
- [x] Check available space before duplicating a dataset
- [ ] Make it so that if a snapshot from the default `bootfs` is cloned *and* promoted, the new dataset should become the default `bootfs`; for added points, have an option to do automatic renaming so the promoted snapshot keeps the name.

**Comment by zdykstra** [comment]
See https://github.com/zbm-dev/zfsbootmenu/tree/help-system for the WIP online help/documentation browser.

**Comment by zdykstra** [comment]
Job control in duplicate process: https://github.com/zbm-dev/zfsbootmenu/commit/6cca613bf51d4852143cdeb2b12c011eb1432b77

**Comment by zdykstra** [comment]
Space calculations in https://github.com/zbm-dev/zfsbootmenu/commit/d5318c2fa73e9a808b288e336a2a7d4615ba86f6

**Comment by ahesford** [comment]
Closed via #101.
