### ISSUE TITLE
How would one set a keyboard layout for `zfsbootmenu`?

### ISSUE THREAD

**Issue by Matthew-Tate-Scarbrough** [zbm-dev/zfsbootmenu#96]
I use the Dvorak layout—I know my password on the normal US layout, but it is still a bit of an impedance sometimes.

**Comment by zdykstra** [comment]
This isn't something I've done before, but it looks like you can control this behavior in the ZFSBootMenu initramfs via [vconsole parameters](https://people.redhat.com/harald/dracut.html#id535798) . If you identify the correct kernel command line parameters, feel free to note them here - I'll add them to a tips-and-tricks wiki entry.

**Comment by Matthew-Tate-Scarbrough** [comment]
Just wanted to give a bit of an update... I have tried everything I can think of—I just can't get the keymap to set for ZFSbootmenu.

**Comment by zdykstra** [comment]
Can you describe a few of the steps you've taken? I can attempt this locally, but I'd like to walk through what you've tried first.

**Comment by Matthew-Tate-Scarbrough** [comment]
I have, so far, attempted editing `ESP/void/refind_linux.conf`; and `/etc/zfsbootmenu/dracut.conf.d` then using `xbps-reconfigure -f zfsbootmenu`.

In both cases, I tried the lines `rd.vconsole.keymap=dvorak`, `vconsole.keymap=dvorak`, and `keymap=dvorak`.
I have not, however, attempted to edit `/etc/dracut.conf.d`.

**Comment by vttfreebsd** [comment]
Hi,
I'm trying zfsbootmenu with **voidlinux** and I put directly in the begining of **/usr/lib/dracut/modules.d/90zfsbootmenu/zfsbootmenu.sh** the "**loadkeys fr**" command to get a french keyboard before generating the initramfs....img.

**Comment by zdykstra** [comment]
> Hi,
> I'm trying zfsbootmenu with **voidlinux** and I put directly in the begining of **/usr/lib/dracut/modules.d/90zfsbootmenu/zfsbootmenu.sh** the "**loadkeys fr**" command to get a french keyboard before generating the initramfs....img.

Did this work?

**Comment by vttfreebsd** [comment]
Yes, this permits me to type the password (my zpool is encrypted) easyly on my French keyboard.

**Comment by zdykstra** [comment]
> Yes, this permits me to type the password (my zpool is encrypted) easyly on my French keyboard.

Thanks for the confirmation. I'll see what I can come up with based on this note.

**Comment by ahesford** [comment]
Is the `KEYMAP` variable defined in `/etc/rc.conf`? I have a custom keymap defined in mine and dracut definitely respects that. You won't need to specify any command-line arguments in that case.

In the worst case, the upcoming ZFSBootMenu 1.8.0 will support arbitrary setup and teardown hooks, so if you can't get the standard dracut i18n module to do the right thing with `rd.vconsole.keymap`, you will be able to write a simple hook script to call `loadkeys` as you like. The problem with these hooks is that they do not run when the countdown timer automatically tries to boot, so you'd have to set `timeout=-1` to force the menu to appear and trigger the hooks to run.

**Comment by vttfreebsd** [comment]
Yes, KEYMAP variable is defined in my /etc/rc.conf.
But as zfsbootmenu.sh is started right after the kernel in initramfs from ESP being loaded, the keyboard is still in the default layout. Any interactive task like zpool password typing or emergency shell launched by zfsbootmenu.sh uses the default layout keyboard.
I don't know how dracut works so my solution is adding "loadkeys fr" in zfsbootmenu.sh. I'm sure you will find a better solution for non US-keyboard  users for the nest version of ZFSBootMenu.
BTW, Thanks for this awesome zfsbootmenu package.

**Comment by Matthew-Tate-Scarbrough** [comment]
I will be interested in a more proper solution in the future, but I can definitely say that modifying `/usr/lib/dracut/modules.d/90zfsbootmenu/zfsbootmenu.sh` is a good enough solution on my part.

To be a little more specific, though probably unnecessary, adding `loadkeys dvorak`, based on vttfreebsd's personal solution, after the shebang and before all else, then reconfiguring zfsbootmenu is, at the moment, good enough for me:

```
#!/bin/bash
# vim: softtabstop=2 shiftwidth=2 expandtab

# set keymap
loadkeys dvorak
```

**Comment by zdykstra** [comment]
I've just tested this (again) locally in the `testing/` VM system, and when I set `rd.vconsole.keymap=dvorak` on the kernel command line and boot ZFSBootMenu with that, the `dvorak` keymap is correctly loaded in the current master branch (soon to be 1.8.0). This relies on the `10i18n` dracut module, which should automatically be included in your ZFSBootMenu initramfs.  Set the key=value on the command line for ZBM, verify that it's there in the recovery shell via `cat /proc/cmdline` and you shouldn't have any issues.

**Comment by Matthew-Tate-Scarbrough** [comment]
What does it mean if the initramfs isn't being passed `the rd.vconsole...` param?

Though I look, using refind, at the parameters that it is supposed to boot ZBM with, they are the correct parameters, but it seems not a one actually is taking effect.

**Comment by ahesford** [comment]
Sounds like rEFInd might be misconfigured. A workaround might be to do the following:
```bash
mkdir -p /etc/cmdline.d
echo "rd.vconsole.keymap=dvorak" > /etc/cmdline.d/keymap.conf
echo 'install_optional_items+=" /etc/cmdline.d/keymap.conf "' > /etc/zfsbootmenu/dracut.conf.d/keymap.conf
generate-zbm
```
By default, dracut modules look at the actual kernel command line at `/proc/cmdline` and also at the snippets in `/etc/cmdline.d` to determine an "effective" command line. If you aren't getting the right values into the real command line, brute-force them into the initramfs with this technique.

The `i18n` modules provided by dracut should honor the value it sess here, unless you're overriding on the actual KCL.

**Comment by zdykstra** [comment]
> > If you don't, that means the initramfs isn't being passed rd.vconsole.keymap
> 
> What does it mean if the initramfs isn't being passed the `rd.vconsole...` param?
> 
> Though I look, using refind, at the parameters that it is supposed to boot ZBM with, they are the correct parameters, but it seems not a one actually is taking effect.

Ahh. If you're using rEFInd to boot a zfsbootmenu.EFI bundle (kernel + initramfs in a single file), it will not pass any parameters to it. It's a 'feature' of rEFInd since it can result in hard-locks under some EFI implementations. You'll have to embed the parameters in the EFI bundle or switch to component builds.

**Comment by Matthew-Tate-Scarbrough** [comment]
> ```shell
> mkdir -p /etc/cmdline.d
> echo "rd.vconsole.keymap=dvorak" > /etc/cmdline.d/keymap.conf
> echo 'install_optional_items+=" /etc/cmdline.d/keymap.conf "' > /etc/zfsbootmenu/dracut.conf.d/keymap.conf
> generate-zbm
> ```

That worked... hmm... I am utterly confounded.  I have been editing the file in `/boot/efi/EFI/void/refind_linux.conf`, though rEFind shows the options in it, it fails to pass any of them when booting ZBM... but what you have mentioned here works for the boot menu but not when booting into the OS completely.

**Comment by ahesford** [comment]
Based on what @zdykstra indicates, just add `rd.vconsole.keymap=dvorak` to the `Kernel.CommandLine` field in `/etc/zfsbootmenu/config.yaml`.

**Comment by Matthew-Tate-Scarbrough** [comment]
> Based on what @zdykstra indicates, just add `rd.vconsole.keymap=dvorak` to the `Kernel.CommandLine` field in `/etc/zfsbootmenu/config.yaml`.

I have tried that, that does nothing, which further confounds me.
